<?php
$section = 'Plays';
$title   = 'End of October';
/*
TODO:
- fix alaine's karaoke choice
- adapt SF2 reference to something jon would really weigh in on
- show matt and jon getting along a little better in the beginning.
- show a littl more of greg and alaine growing together as a means of growing apart from the larger group. maybe they are invited to another group activity and decline to spend time together.
*/
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content" class="mb20">
    <h2 class="mb20">
        <span>End of October, by Matt Harrison</span>
        <span class="right">11/04/09</span>
    </h2>
    <div class="auto mb20 w500">
        <p class="ml1of2 underline">Cast of Characters</p>
        <ul>
            <li class="flex mb10">
                <p class="size1of3 underline">Skeleton:</p>
                <p class="mb0 size2of3">23-year old man; wears a black t-shirt with the word SKELETON written across the front in plain white letters.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Captain Picard:</p>
                <p class="mb0 size2of3">21-year old man; wears a dark red long-sleeve shirt with a Star Trek emblem sloppily drawn on the breast pocket.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Gandalf:</p>
                <p class="mb0 size2of3">22-year old woman; Picard's wife; wears a gray t-shirt with the outline of a long beard tracing down from the neckline.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Bruce Willis:</p>
                <p class="mb0 size2of3">23-year old man; wears a white tank top undershirt with a few grease spots and a few fake blood spots.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Mr. Pink:</p>
                <p class="mb0 size2of3">20-year old man; wears a black blazer over a white t-shirt with a fake collar and a skinny tie drawn down the center. He carries a heavy black BB gun.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Robocop:</p>
                <p class="mb0 size2of3">25-year old man; wears a gray short-sleeve shirt, gray jeans, a black cumberbund, and a gray beanie pulled down over his eyes.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Supergirl:</p>
                <p class="mb0 size2of3">21-year old woman; wears a blue tube top, adorned with a Superman "S" patch, over a white t-shirt with fake cleavage drawn on the front.</p>
            </li>
            <li class="flex mb10">
                <p class="size1of3 underline">Xena:</p>
                <p class="mb0 size2of3">22-year old woman; wears a brown bikini top over a tan t-shirt and a brown skirt with fringe; carries a large round ring cut out of gray cardboard.</p>
            </li>
        </ul>
    </div>
    <div>
        <p class="ml1of2 underline">Scene</p>
        <p class="auto mb20 w700">Picard, Skeleton, and Mr. Pink sit atop tall stools along a bar area in Picard and Gandalf's apartment. There are scattered bottles of soda and alcohol, snacks, candy, and other items strewn about the countertop. Off to the side a little, a life-size skeleton decoration hangs two feet off the ground, from a noose tied to the ceiling. Music plays in the background, and Picard dances a little in his seat, entertaining Mr. Pink. Both are facing away from the bar. Skeleton's back is turned, his head down, reading from a book on the counter. As the play goes on, minor characters wander across the stage at random intervals, some silently acknowledging the group, others ignoring them.</p>
        <p class="ml1of2 underline">Time</p>
        <p class="auto mb20 w700">October 31, 2007. Night.</p>
    </div>
    <section class="ml1of2">
        <p class="underline">ACT I</p>
        <p class="underline">Scene 1</p>
    </section>
    <section class="auto w700">
        <p>SETTING: A corner of Picard and Gandalf's apartment during a Halloween party.</p>
    </section>
    <section>
        <p class="auto w400">(MR. PINK shoots at PICARD with the unloaded BB gun.)</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto mb0 w400">(indicating himself)</p>
        <p class="auto w500">So, what's the best costume you've seen so far?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">There was a guy dressed as Captain Picard, I think. That was a pretty great one.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Isn't that what your costume is?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Oh, yeah, that must be who I was thinking of.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">You can't be your own favorite costume.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">YOU can't be my own favorite costume.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Did you see my skinny tie?</p>
        <p class="auto w400">(BRUCE WILLIS approaches and takes the fourth stool along the bar.)</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Hey. Did you just get here?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Yeah, sorry. I got caught up talking to my dad. Do you know if Christina is here yet?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Yeah, she was out on the porch when I went to go smoke.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Cool. I'm gonna go find Christina real quick.</p>
        <p class="auto w400">(WILLIS reaches over and snatches the book from out of SKELETON's hands.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto mb0 w400">(spinning around on the stool)</p>
        <p class="auto w500">Hey, I was reading that.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">It's a party, man. Who brings a book to a party?</p>
        <p class="auto w400">(WILLIS glances down at the book in his hands, inspects it, flips it over and reads from the back cover.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="ml1of2">I'll be back.</p>
        <p class="auto w400">(WILLIS leaves the stage.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Is he with Christina now?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto mb0 w500">Not really.</p>
        <p class="auto mb0 w400">(Pause.)</p>
        <p class="auto w500">I'm gonna go smoke.</p>
        <p class="auto w400">(MR. PINK takes a shot of something.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Again?</p>
        <p class="auto w400">(MR. PINK leaves the stage.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">When did Jon start smoking for real?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Ehh.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">So what did you think of "Electric Sheep"?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">It was pretty good. Alaine's reading it now. I'll get it back to you when she's done.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I just saw the movie for the first time. Kinda slow.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I love that goddamn movie.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">It doesn't make a lot of sense.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">That's what I love about it.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Yeah, I'm glad I finally saw it, but I still like the book better.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Well, ya know, I just skimmed it.</p>
        <p class="auto w400">(WILLIS returns with a beer bottle in his hand. He drops SKELETON's book back on the countertop behind him.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">What are we talking about?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Blade Runner, the best movie ever.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Oh man, the book was even better.</p>
        <p class="auto w400">(PICARD's wife, GANDALF, approaches and puts her arm around her husband's chair.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Hey, dudes.</p>
        <p class="auto w400">(PICARD tips off his chair to do a little dance for her.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Hey, Alaine. Do you know if you guys have any juice?</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Yeah, we got some OJ for the screwdrivers.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Great, thanks.</p>
        <p class="auto w400">(SKELETON leaves the stage. MR. PINK returns.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">We're gonna start the movie soon if you guys wanna come to the other room.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Is Jason gonna have the hockey mask in this one? I don't give a shit about pre-mask Jason.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">You can't completely dismiss number two. He kills a guy in a wheelchair.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">That could be anyone under the sack mask.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">It could be anyone under the hockey mask.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">No, no. That's no mask. That's his face.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Maybe he had the hockey mask on under the sack mask.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Not hockey mask. Hockey face.</p>
        <p class="auto w400">(SKELETON comes back with a cup. He stands next to MR. PINK, who has taken his seat.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w400">(to MR. PINK)</p>
        <p class="auto w500">God, Jon, you smell like smoke.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Yeah, and it's fucking delicious.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Gross.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Are you drinking a screwdriver?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">It's just juice.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Aw, man. You're wasting it.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Fuck off.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Careful. Let's not let this turn into a juice war.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">A juice war actually sounds kinda awesome.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Juice war!</p>
        <p class="mb0 ml1of2">PICARD and GANDALF</p>
        <p class="auto w500">Juice war! Juice war! Juice war!</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Fuck it. I'm having one.</p>
        <p class="auto w400">(MR. PINK leaves to fix himself a drink.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Anyway, we wanna start the movie soon.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">OK, we'll be in.</p>
        <p class="auto w400">(GANDALF leaves.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Why are all these people here?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">It's a party.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Why can't we just watch a movie? Why do we have to get a bunch of drunk people involved?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Drunk people are funny.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Drunk people are only funny to drunk people.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">That makes you the exception.</p>
        <p class="mb0 ml1of2">Picard</p>
        <p class="auto w500">In the land of the drunk, the one-eyed drunk is... drunk?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Poignant.</p>
        <p class="auto w400">(MR. PINK returns.)</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Dude. You won't believe what just happened.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I bet I will.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Somebody in a Robocop costume just puked all over...</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Awesome.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">No, dude, right into the whiskey bottle!</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">What?!</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">He went to take a drink and just puked right into the bottle, all over his hands, his costume, everything!</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto mb0 w500">Oh God, I think I smell it.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto mb0 w400">(sarcastically)</p>
        <p class="auto w500">Well, that's great. That just sounds great.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Don't worry. It mostly just got on the linoleum.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">You didn't clean it up?!</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I'm not worried.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Alaine's gonna be pissed.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Anyways, somebody needs to go get some more whiskey.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto mb0 w400">(to SKELETON)</p>
        <p class="auto w500">Oh, hey. Did I tell you I found my old X-men comics?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">What? Like which ones?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">All my old 90s comics. I found a whole box of 'em at my mom's house.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Shit. Can I have them? You gotta let me have those.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Hell no.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Are they here? Where are they? Show me.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Yeah, they're in my room. C'mon.</p>
        <p class="auto w400">(PICARD and SKELETON go out.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">So... how've you been? We haven't hung out in a bit.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Eh... I'm all right.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">You staying with your mom again?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Yeah, I still need to get some of stuff from Meg's, though. Some clothes and stuff.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Did I tell you that I saw her last week?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Yeah? Just up working at the mall?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Nah, we went and got burritos.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">She called you?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Yeah, it was fun. Have you been to the burrito bar yet?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Uh, yeah. She... me and her used to go there.</p>
        <p class="auto w400">(Pause. MR. PINK gulps down the rest of his drink.)</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto mb0 w400">(indicating his glass)</p>
        <p class="auto w500">I'm gonna go get another one.</p>
        <p class="auto w400">(MR. PINK leaves. WILLIS looks around the room, watching people for a few moments. SUPERGIRL approaches.)</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Hey, Zack. Cool costume. Who are you?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">I'm Bruce Willis.</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Oh, cool! Like from The Fifth Element? I love that movie!</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">From Die Hard.</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Oh, I've never seen that. Isn't that with, like, Steven Seagal?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">No, no, no. You have to see it. It's a classic. You should come over this week and I'll show you.</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Yeah, that would be fun. Or, you know what? You could come to karaoke with us on Friday. We go every week. I love it.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Sounds like fun.</p>
        <p class="auto w400">(GANDALF returns.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Zack, did you see where Greg went? Some asshole puked all over my kitchen floor.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">They went in the back room to look at comics.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Not the comics. This is supposed to be a party.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Hey, would you wanna come to karaoke with us on Friday night?</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Like where? Do they have metal? I will sing the shit outta some Slayer.</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Who?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Probably. Apparently they do it every weekend.</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto mb0 w400">(dismissively)</p>
        <p class="auto w500">Well, not every weekend.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">OK, well let me know.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Back room.</p>
        <p class="auto w400">(SKELETON returns with a stack of comics.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Hey, Alaine.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Hey, nerd.</p>
        <p class="auto w400">(GANDALF leaves. SKELETON stacks the comics on the counter with his book. WILLIS starts eyeing the comics.)</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Oh, you like comics, Zack? What do you think of my Superwoman costume?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">There's no such character as Superwoman.</p>
        <p class="auto w500">No, like from Superman.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Uhh...</p>
        <p class="mb0 ml1of2">SUPERGIRL</p>
        <p class="auto w500">Anyway, I'll see you later, Zack. I love your Steven Seagal costume.</p>
        <p class="auto w400">(Supergirl wanders away.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Gross, dude. You're Steven Seagal? I thought you were supposed to be Bruce Willis in Die Hard.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Well, you heard what Superwoman said.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">"Superwoman."</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">You know, there actually was a Superwoman on Earth-2.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto mb0 w500">Whatever. Superman isn't even a comic book anymore. It's a Shaq tattoo.</p>
        <p class="auto mb0 w400">(Pause.)</p>
        <p class="auto w500">I'll be right back.</p>
        <p class="auto w400">(SKELETON leaves. MR. PINK and a visibly drunk ROBOCOP enter.)</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">Hey, man. Cool party, huh? I love Halloween.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Yeah, me too. I especially love whiskey bottles filled with puke.</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">Dude! It's so weird you said just that! I was just puking into a whiskey bottle like five minutes ago! That's so weird.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Yeah, weird.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Robocop's gonna buy us some more whiskey.</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">Yeah, man. You gotta have whiskey. </p>
        <p class="auto w400">(MR. PINK laughs, WILLIS chuckles.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Yeah, that's great. Let me know when you're getting ready to puke in the next one. I'd like to watch.</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">Sure, man. No problem.</p>
        <p class="auto w400">(Robocop and MR. PINK both laugh heartily. WILLIS chuckles again. PICARD and GANDALF approach.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Oh good, look who it is!</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">You can't be mad at Robocop, honey. Look at his beautiful face.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Who even invited this guy?</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">Hey, man. Be cool. It's a party.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">No, "man," didn't you hear? The party's not until tomorrow night.</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">What? No way, man. You're just messing with me.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">No, dude. She's right. You didn't hear about this? The party got moved to tomorrow.</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w400">(laughing)</p>
        <p class="auto w500">No, man. You can't trick me. Tonight is Halloween, man. Look at all the costumes.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">What costumes?</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Yeah, what costumes do you mean?</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">You guys are crazy, man.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">They're just kidding, dude. C'mon, let's go get that whiskey. We'll be back later, guys.</p>
        <p class="auto w400">(WILLIS takes the BB gun out of MR. PINK's hand and lays it on the counter.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Better leave this here.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Or you could just store it in Robocop's thigh.</p>
        <p class="mb0 ml1of2">ROBOCOP</p>
        <p class="auto w500">Do what?</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">I won't be upset if you lose Robocop in some bushes on the way back.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto mb0 w500">Whatever.</p>
        <p class="auto mb0 w400">(to ROBOCOP)</p>
        <p class="auto w500">C'mon.</p>
        <p class="auto w400">(MR. PINK and ROBOCOP leave the party.)</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">C'mon, honey. It's not a party without Robocop.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">I don't need this sloppy motherfucker puking all over my house.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I think we do. I think we need him.</p>
        <p class="auto w400">(PICARD starts doing a robot dance for GANDALF. He starts to win her over.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">All right, well, I'm gonna go get the movie started.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">We're not gonna wait for Jon to get back?</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Bah. OK, ten minutes. That's it.</p>
        <p class="auto w400">(GANDALF leaves.)</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto mb0 w400">(turning to WILLIS)</p>
        <p class="auto w500">So.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">So.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Seen any good costumes?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Some.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I saw a pretty good ghost.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">You mean the sheet with eye holes?</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Yeah. Super innovative.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">So clever. Maybe next year he'll just pop in some vampire teeth.</p>
        <p class="auto w400">(SKELETON returns.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Where've you been?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Nowhere.</p>
        <p class="auto w400">(SKELETON adds some more of PICARD's comics to the stack on the counter.)</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I told you those X-Force ones were good.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">In like a cheesy 90s way.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">In a totally perfect way.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Dude, these decorations are nuts. Where did you get this thing?</p>
        <p class="auto w400">(He swings the hanging skeleton. It sways back and forth like a pendulum as the conversation continues.)</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I borrowed it from my dad's classroom.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Oh, right. That's a really good idea.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">I'm glad you don't have all that stretched cotton around. I hate that stuff.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">What, like the webs?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Is that what that's supposed to be? The chunky cotton everywhere?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Are you kidding me?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">How should I know? It doesn't look like a web. It doesn't look like anything.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I have to remember to put up some chunky cotton next year.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">No man, don't do it. That stuff sucks.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I have to now. I have to.</p>
        <p class="auto w400">(MR. PINK returns alone.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Hey, where's your friend? Did he get arrested?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto mb0 w400">(a little drunk now)</p>
        <p class="auto w500">Hey, fuck you, OK? What's your problem tonight?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">So, you found the whiskey, then?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I don't have a problem. All my beverages are completely free of vomit.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">It's a fucking party, Matt. Why don't you want anyone to have any fun?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Cause your idea of fun ruins everyone else's fun.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">It's just you, Matt. Everyone else is having a good time.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I'm having a good time.</p>
        <p class="auto w400">(MR. PINK knocks his BB gun off the counter and it clatters loudly on the ground.)</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Why don't you watch where you going?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Why don't you take your book and go read at home?</p>
        <p class="auto w400">(WILLIS steps between them and nudges MR. PINK back.)</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">C'mon man, let's just go watch some Jason. Jason will cheer you up. Jason's a fucking prince.</p>
        <p class="mb0 mb0 ml1of2">MR. PINK</p>
        <p class="auto mb0 w400">(to himself)</p>
        <p class="auto w500">It's a fucking party, man.</p>
        <p class="auto w400">(PICARD leads MR. PINK out.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto mb0 w400">(turning to SKELETON)</p>
        <p class="auto w500">What's with you two?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I just... I don't like parties.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">You? Really?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Halloween was so much fun when it was just us. We'd watch a bunch of stupid movies and that was that. Now I'm surrounded by drunk assholes. How is that better?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">You just don't like that your friends have other friends.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">"Oh, I drank so much last night. Have you heard of this beer? Did you try the new whatever?" What's the fascination?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">It's just what people our age do.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I don't relate to these people. It makes me want to forget the whole thing. I'd rather just read my goddamn book.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">You just want us all to stay twenty forever.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">What's wrong with that?</p>
        <p class="auto w400">(XENA enters the scene.)</p>
        <p class="mb0 ml1of2">XENA</p>
        <p class="auto w500">Hey, Zack! Come dance with us!</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto mb0 w400">(still to SKELETON)</p>
        <p class="auto w500">Are you gonna go home?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I dunno. Maybe pretty soon.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">All right. Come find me when you're leaving, OK?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">K.</p>
        <p class="auto w400">(WILLIS leaves with XENA. SKELETON turns his back to the party and opens his book on the countertop. After a few moments, GANDALF enters.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">What's with Jon?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Hell if I know.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">He seems pissed.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Yeah. I kinda think we're at different parties.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Your type of party is not a party.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Yeah.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">You gonna come watch the movie?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Maybe in a little bit. You can start without me.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Oh, we already did.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">That's fine.</p>
        <p class="auto w400">(MR. PINK returns alone.)</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">Be nice, guys.</p>
        <p class="auto w400">GANDALF leaves.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Hey.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Hey.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Look, let's do something tomorrow. You wanna go see a movie?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">I don't have any money.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I could cover you.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">I dunno. I haven't been watching a lot of movies lately. Anyway, I have band practice.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">You guys got some shows coming up?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">A couple. Mostly we gotta get ready to record.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">That'll be cool.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Then you won't have to come to the shows anymore.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I like the band a lot, I just can't stand going to bars.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">I know.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">So, no movie, then?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Christina's party is on Saturday. You should come out.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Nah, I don't know those people.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">You only know the four of us.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">That's plenty.</p>
        <p class="auto w400">(GANDALF, PICARD, and WILLIS return.)</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto mb0 w400">(to Matt)</p>
        <p class="auto w500">Dude, is there such a game as Street Fighter I?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">Huh?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Alaine says there's no such thing as Street Fighter. She says the series started with number two.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">It did. It totally did. Have you ever played a number one?</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">I guess I haven't.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Well, neither have I... but there has to be one.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">It's a conspiracy. They wanted to seem all mysterious.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">The original came out in the mid 80s. You had to play as Ryu. Player two had to be Ken. The sequel was the first fighting game where you got to choose your character. It basically invented the modern fighting game.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">I knew it.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">No way. I have to play as Guile.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">What? Guile sucks.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I need to have my Sonic Boom and I need to have my flat top.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Guile wasn't even in the original.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">What? It's not Street Fighter if there's no Guile. I'm on Alaine's side. I refuse to acknowledge this game.</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">And the final boss was Sagat.</p>
        <p class="mb0 ml1of2">PICARD, WILLIS, GANDALF, and SKELETON</p>
        <p class="auto w500">What?!</p>
        <p class="auto w400">(XENA enters.)</p>
        <p class="mb0 ml1of2">XENA</p>
        <p class="auto w500">Zack, you guys are missing Jason.</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Can't miss Jason.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">I always miss Jason.</p>
        <p class="mb0 ml1of2">GANDALF</p>
        <p class="auto w500">But Jason never misses you.</p>
        <p class="mb0 ml1of2">PICARD</p>
        <p class="auto w500">Are you saying that his machete swipes are accurate, or are you saying that he doesn't love me back?</p>
        <p class="mb0 ml1of2">WILLIS</p>
        <p class="auto w500">Matt, Jon, you guys coming?</p>
        <p class="mb0 ml1of2">MR. PINK</p>
        <p class="auto w500">Hell yeah, I'm coming.</p>
        <p class="mb0 ml1of2">SKELETON</p>
        <p class="auto w500">All right, yeah. I'm coming.</p>
        <p class="auto w400">(As they leave, someone brushes against the hanging skeleton decoration. For several moments, the only movement on stage is the gentle swaying of the skeleton.)</p>
    </section>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
