//Ships
deathstar = {
	'character': 'deathstar',
	'ship': true,
	'death': explosion,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': green,
	'weaponOffsetLeft': [2, 3],
	'weaponOffsetUp': [3, 0],
	'weaponOffsetRight': [5, 3],
	'weaponOffsetDown': [3, 5],
	'width': 90 * magnification,
	'height': 40 * magnification,
	'frameWidth': 10 * magnification,
	'frameHeight': 10 * magnification,
	'moveFrameCount': 8,
	'speed': 4,
	'speedMin': 4,
	'speedMax': 4
};

deathstar6 = {
	'character': 'deathstar6',
	'ship': true,
	'death': explosion,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': green,
	'weaponOffsetLeft': [2, 3],
	'weaponOffsetUp': [3, 0],
	'weaponOffsetRight': [5, 3],
	'weaponOffsetDown': [3, 5],
	'width': 90 * magnification,
	'height': 40 * magnification,
	'frameWidth': 10 * magnification,
	'frameHeight': 10 * magnification,
	'moveFrameCount': 8,
	'speed': 4,
	'speedMin': 4,
	'speedMax': 4
};

destroyer = {
	'character': 'destroyer',
	'ship': true,
	'death': explosion,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': red,
	'weaponOffsetLeft': [16, 14],
	'weaponOffsetUp': [15, 16],
	'weaponOffsetRight': [12, 15 ],
	'weaponOffsetDown': [15, 12],
	'width': 60 * magnification,
	'height': 120 * magnification,
	'frameWidth': 30 * magnification,
	'frameHeight': 30 * magnification,
	'moveFrameCount': 1,
	'speed': 1,
	'speedMin': 1,
	'speedMax': 5
};

falcon = {
	'character': 'falcon',
	'ship': true,
	'death': spritz,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': green,
	'weaponOffsetLeft': [5, 7],
	'weaponOffsetUp': [7, 6],
	'weaponOffsetRight': [8, 7],
	'weaponOffsetDown': [7, 8],
	'width': 75 * magnification,
	'height': 60 * magnification,
	'frameWidth': 15 * magnification,
	'frameHeight': 15 * magnification,
	'moveFrameCount': 4,
	'speed': 8,
	'speedMin': 8,
	'speedMax': 15
};

tie = {
	'character': 'tie',
	'ship': true,
	'death': spritz,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': red,
	'weaponOffsetLeft': [0, 3],
	'weaponOffsetUp': [3, 0],
	'weaponOffsetRight': [5, 3],
	'weaponOffsetDown': [3, 5],
	'width': 35 * magnification,
	'height': 28 * magnification,
	'frameWidth': 7 * magnification,
	'frameHeight': 7 * magnification,
	'moveFrameCount': 4,
	'speed': 8,
	'speedMin': 8,
	'speedMax': 12
};

vadertie = {
	'character': 'vadertie',
	'ship': true,
	'death': spritz,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': red,
	'weaponOffsetLeft': [0, 3],
	'weaponOffsetUp': [3, 0],
	'weaponOffsetRight': [5, 3],
	'weaponOffsetDown': [3, 5],
	'width': 35 * magnification,
	'height': 28 * magnification,
	'frameWidth': 7 * magnification,
	'frameHeight': 7 * magnification,
	'moveFrameCount': 4,
	'speed': 10,
	'speedMin': 10,
	'speedMax': 12
};

xwing = {
	'character': 'xwing',
	'ship': true,
	'death': spritz,
	'weaponType': 'projectile',
	'projectile': 'laser',
	'weaponColor': green,
	'weaponOffsetLeft': [1, 4],
	'weaponOffsetUp': [4, 1],
	'weaponOffsetRight': [8, 4],
	'weaponOffsetDown': [4, 8],
	'width': 45 * magnification,
	'height': 36 * magnification,
	'frameWidth': 9 * magnification,
	'frameHeight': 9 * magnification,
	'moveFrameCount': 4,
	'speed': 8,
	'speedMin': 8,
	'speedMax': 12
};
