<?php
$section = 'Stories';
$title   = 'Saturday';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <h2 class="mb20">
        <span>Saturday, by Matt Harrison</span>
        <span class="right">12/15/09</span>
    </h2>
    <div class="auto mb20 w700">
        <p>Matthew awoke on Saturday morning to thoughts of his former love, and wound his limbs around her successor, his partner of the past five years. He pulled his wife close, and her discomfort registered as little, close-lipped moans that crept to life without disturbing her sleep. Laura slept on her right side, facing away from him, toward the window, where mid-morning light struggled in from between the layered slats. Forcing his arm beneath her neck and burying it up to his chest, he curled his fingers up around her pale, slender shoulder. His left arm he draped around her waist, tugging at her core to hold her against himself.</p>
        <p>"I'm sleeping," she said.</p>
        <p>She'd spent the night wearing his undershirt, as was her custom. Each night, when they would climb into their bed, the one place where bare skin was worth the chill in the air, she'd pull the shirt over his head and let it slide down over her own body. In the morning, beneath that graying cotton, he wrapped his fingers around her side, squeezing her ribs and feeling them flex. He inhaled slowly at her neck, where day-old perfume lingered, smelling artificial but sweet.  He brought his fingers to her smooth, brown hair, wrapping it up into a thick cord and pulling at it firmly.</p>
        <p>"Ow. Matty, stop."</p>
        <p>Stirring to life, she rolled over to meet his eyes. He moved back to accommodate her. He smiled to see her face. She smirked with mock annoyance, awake enough now to forgive his affection. Once tempted by the pull of heavy sleep, she always preferred to collapse into the stillness, mostly ignoring her husband's flirtations, but each morning, as she adjusted to the light of day, she would cross that invisible boundary into mostly-consciousness, and validate his affections with that little look that kept him coming back. Rolling onto her back again, she folded her shoulders down, arching her spine like a cat in reverse.</p>
        <p>He slid his right hand under the small of her back, and without letting her finish stretching, he curled her around onto his body. He felt her weight, a small, comfy package, floating on his chest. She kissed his forehead, her dry, pink lips wrinkling on his brow.</p>
        <p>Sitting up reluctantly, Laura moved to the edge of the bed, where the elastic piping of the shrunken, purple sheet had drawn back from beneath the mattress. She bent forward and scratched at the chin of her small, black and brown-marbled cat, who sat nuzzling her ankles. Laura turned again to see Matthew watching her, smiling a bit. She scratched under his chin, too. The small, metallic sound of her nails twisting in the short, coarse hairs of his beard played in his head like the plinking of a music box. There was something satisfying about it.</p>
        <p>When Laura left the room to begin the transition into the Saturday noon-hour, Matthew lay back in their bed. He slid over to her side, propping his head up on her much spongier pillow, and stared at the ceiling. He thought of the smooth skin on Laura's white legs, the muscles of her back, the shapely slope of her hips. Fourteen steps away already felt too far. Then he thought again of Jane.</p>
        <p>His dream had already lost most its clarity, but he dwelled on the echo of the serenity he'd felt, lying there, believing he'd resolved a long-standing dissatisfaction with the way things had ended, a nagging twinge that they hadn't given it the real chance it deserved. He'd loved her, but she'd never been entirely comfortable with it, though he'd forced himself to spare her the words.</p>
        <p>"Your turn," Laura said. "Time to get up." Her legs were bare.</p>
        <p>As Matthew lumbered to his feet, his wife returned to her side of the bed, resting on top of the heavy comforter.</p>
        <p>"You're not going back to sleep, are you?" he asked.</p>
        <p>"Of course not." She closed her eyes.</p>
        <p>Matthew closed the bathroom door. The knob was flimsy, cheap to begin with and never properly attached. He banged on the door of the medicine cabinet, which didn't close easily, thanks to years of the sloppy, milk-colored paintjobs that buffered each new resident of the small apartment. It didn't seem to bother Laura, who tended to leave the cabinet open a crack after she'd restored her hairbrush each morning. She never fully closed the cap of the toothpaste, either. A part of Matthew suspected that she did it consciously, a subtle prompt to make sure he bothered to brush his teeth, a reminder that didn't make her feel like she was nagging. He thought it sweet, if that was the case, but he never mentioned it to her. He preferred to find the mystery again each day.</p>
        <p>With the door of the cabinet forced back into place, correcting the angle of its mirrored surface, Matthew elected to stare at himself before bothering with hygiene. His dark hair was short but not symmetrical, sleep having matted it to his head on one side in a way that intensified the effect of an already troublesome cowlick. His eyes were also dark, and he thought they seemed dramatic. A few fuzzy strands, not recently plucked, bridged the gap between his eyebrows, which were otherwise bold. People had often told him that he had strong eyebrows, which struck him as an odd, reaching sort of compliment, but secretly he agreed. His beard was neat-looking enough, deep brown flecked with copper wire, until the point where it met his neck, from which neglected stubble began to curl up. He watched his own eyes, trying to hold onto the small but potent melancholy that had interrupted the lazy flow of his weekend thoughts. He caught an orange flash in a deep corner of the mirror, and glanced around his shoulder.</p>
        <p>Over the lip of the bathtub he saw his cat, a long-haired rascal, sitting with uncommon poise, staring, a question in his diamond eyes. The cat's ear twitched, and the moment escaped. Matthew shifted back to the sink and turned on the faucet. He let the water warm over his hands, then rubbed them down his face, pushing on his eyes a little.</p>
        <p>"Are you gonna shower?" Laura asked when he emerged a moment later.</p>
        <p>"No. I'll just wear my hat," he answered, filling his eyes with sarcastic pride. She made a put-on, irritated noise.</p>
        <p>"Fine. I'll be out in a minute. Wanna get breakfast?"</p>
        <p>"I could go for a bagel sandwich today."</p>
        <p>"You say that like there's ever a day when you might not."</p>
        <p>"Well, sometimes I prefer an omelet?"</p>
        <p>Matthew walked across the bare floor of their living room wearing nothing but a pair of plaid boxer shorts, his choice of pajamas. It was a large room, actually two smaller spaces separated by only a weak barrier that extended twelve inches from the ceiling and walls. From a pile of sorted but unfolded laundry that was arrayed across the maroon surface of the loveseat, he produced the previous night's pair of khaki pants, scooped them on and fastened the clasp. Once appropriate for the office, the pants were now dangerously thin at the knees, and where they scraped the floor beneath his heels, they were shredded to strings.</p>
        <p>He stretched another worn old undershirt across his frame and tugged at the tail, which sat uncomfortably high, barely tenting his waistband. Rummaging through the clumps of wrinkled colors, he remembered DC, where Jane had stolen a shirt for him from a museum gift shop. I like those FBI shirts, he'd told her as they sifted through the clear plastic bins of knickknacks at the counter. I might buy one. Don't, she'd warned. The clerk came by, folding discarded garments. Don't bother, Jane had said. Oh, I see, thought Matthew.</p>
        <p>By the window of the apartment, he held his FBI shirt at arms length, pinching a shoulder in each hand, inspecting it, considering it. He tossed it over the wide, rounded arm of the couch and grabbed a red Seattle shirt instead. He pulled it on, then buried the whole assemblage under a generic long-sleeve.</p>
        <p>From atop a low bookcase around the protruding wall, he retrieved an old, warped stocking cap, a largish book jutting out from within. He floated the thick stack of paperbound pages over toward a low bench nearby, where it landed with a clap.</p>
        <p>From within the hat, he retrieved a series of personal artifacts that he distributed to their customary places around his body. He placed a fake leather tri-fold wallet in his back right pocket. He clipped a cheap carabiner, bearing five keys, to the empty belt loop to the left of his fly. A small, withered notebook, no bigger than his palm, he returned to its home in his right front pocket.  The final piece, an expensive black drawing pen, he held by its metal clip in the crooked space between two teeth in the side of his mouth.</p>
        <p>Goddamn dog, he thought, fingering a group of tiny holes that distorted the shape of the hat. For years, whenever he'd entered a comfortable space where he intended to spend more than a few minutes, he'd removed this same set of items from his pockets, and using the hat from his head as a soft little cubby, stored the whole capsule on some surface near an entryway.</p>
        <p>Fidgeting with the pen in his busy hands now, he remembered having found this same pocket of belongings scattered across Jane's floor one morning, the sanctity of its threaded shelter broken. With her mother out of town, Jane had invited him to spend the night in her otherwise empty home. It made her mother feel better, she'd said, that she wouldn't be in the house alone. He'd found that odd. His own parents would not have approved.</p>
        <p>It had been a quiet sort of night. Jane had played a record for him, an album he'd always heard about but never bothered to investigate. Something about the context of the evening had made the music sound perfect, untouchable. He'd never heard the album since, had avoided it, hoping to preserve the experience. He didn't remember the notes, the melodies, just the atmosphere in the room that night.</p>
        <p>When they'd come downstairs the next morning, he'd found Jane's beloved dog, a shelter mutt with sad eyes and an abrasive complexion, napping contentedly amid the strewn supplies. The wallet was wet with saliva, and some of the stitching along the top had been torn out. The carabiner was bent, warped along the contours of the dog's deepest molars. A few tiny pages lay apart from the notebook, where they'd detached from its gluey spine. And the worst offense by far, the hat, that cozy friend, a companion equivalent in his mind to the dog itself, was chewed through the crown.</p>
        <p>Standing in the crook of his segmented living room, Matthew considered that Jane's dog might have been what first influenced him to store his cache of personal effects on higher surfaces, like this waist-level bookcase. He arranged the hat in front of himself, an inch of brim, the crossed seams a measured grid, chew marks at the back left, and stretched it back so that it gripped his head just behind the hairline.</p>
        <p>He moved into the kitchen, and moved a glass from the high, open cabinet to the counter. As he opened the refrigerator door, a white swirl of cold air escaped, a dramatic flare that made a featured player of Laura's carton of soy milk, a stage of the white metal rack. He nudged the carton aside, retrieving a plastic jug of juice instead, and filled his glass. He stood in place and took a few successive gulps.</p>
        <p>I have to tell you something, Jane had said. They were on their way to have lunch with two friends of hers, in town for the weekend. They'd moved away to some nearby minor metropolis, and Jane thrilled at the prospect of the strange and exciting people they'd been meeting.</p>
        <p>Her friend would be smoking cigarettes, she said, and she'd need to participate. She thought it a confession, a great burden relieved, and when he told her that he'd seen the package in her purse some days before, she felt betrayed, couldn't understand why he hadn't made his objections known, hadn't tipped his hand. He felt a little betrayed, too.</p>
        <p>Until that afternoon, he'd managed not to reflect on his sense that her lust for adventure would carry her places that he wouldn't be willing to go. He preferred not to acknowledge it, to continue to believe her purely his, that he alone could make her happy.</p>
        <p>The restaurant had been miserable. The group chatted on, absorbed with each other, never noticing his silence. He couldn't bear to witness their bond, so personal but so communal, so he focused his attention on the smoke streaming from their cigarettes, climbing upward in thick columns to mingle in the cloud above. It was easy for him to imagine them all in some city café together, far away from him.</p>
        <p>Matthew moved into the narrow hallway of the apartment, which ran the ten feet between the only bedroom and the only bathroom, an inner division of the apartment set behind the main atrium. The bathroom door stood open against the tile wall, and the drumming sound of the shower swept through the apartment's throat. Matthew watched Laura's color beyond the plastic curtain, a warm, wet fog forming between them. The boards spoke beneath him as he approached.</p>
        <p>"Changed your mind?" Laura asked.</p>
        <p>"Couldn't resist," said Matthew. Through a gap where the curtain failed to meet the wall, he pulled her away from the water a little. For a moment, he held his forehead against her cheek, ignoring the stray beads that sprinkled his face and shoulders. Then he kissed her lips and backed away again.</p>
        <p>From the window in the front room, he surveyed the empty courtyard. It was a four-story cavern formed by three walls of toothy brick, still managing to preserve their tenuous grasp on the many air conditioners that had recently begun their winter sleep. Little birds flicked back and forth between mostly sleeveless branches, bobbing with each renewed perch. A few of the blocky stones along the walkway had shifted out of place.</p>
        <p>He thought of the sidewalk downtown, where three weeks prior he thought he'd seen Jane standing among the students and business professionals. She wore stylishly oversized sunglasses that obscured her face, daring him to believe it was another phantom. In any case, across that busy block, she hadn't noticed him.</p>
        <p>He'd slowed his pace, allowing himself time to watch her. Her posture was familiar. She shifted from one leg to the other with a jerk of her hips that somehow managed to seem graceful. She let her cigarette hang loosely between the first and second finger of her right hand, her wrist cocked back.</p>
        <p>Matthew returned to the bedroom, where his wife was trying on shirts. Laura was still adjusting to adulthood, experimenting with garments that draped in odd ways, slung across here and there, or which bore strange flourishes. She had started buying shoes. Matthew thought she looked like a woman, a wife, and while he hadn't necessarily anticipated this change, he had surprised himself by accepting it without anxiety.</p>
        <p>Laura stripped off another layer, a white top with short, lace sleeves that bloomed from her shoulders, like a prom dress hoping to function as daywear. Her wet hair flapped against her neck heavily.</p>
        <p>"What was wrong with that one?" he asked, teasing her a little.</p>
        <p>"Something about the shoulders," she confirmed.</p>
        <p>"Why would you buy a shirt like that if you're not comfortable being seen in it?"</p>
        <p>"I can always take it back."</p>
        <p>"That's not a good reason to buy something." He chuckled to himself as he wandered back into the front room, remembering to catch his book from the bench on his way through the frame.</p>
        <p>Seating himself on the larger couch, he shoved aside the blanket they'd shared the night before, when their shins had crossed from opposite ends of the pillowed seat. Placing his thumb on the overhanging edge of the bookmark, a thin, curling receipt bearing Laura's scribbled portrait of him in fine black lines, he tipped the book and let the two partitions separate. Fixing his eyes on the left hand page, he began to follow the words. A minute later, his eyes were still tracing the lines, but he no longer registered their meaning.</p>
        <p>That day on the sidewalk, Jane had been chatting with a young woman he didn't recognize, probably some old friend she regretted not spending more time with. She'd never had enough time to keep up with them all. We should have lunch, she'd be saying. He imagined the two girls growing close again, over a period of weeks, the pleasure of recapturing an intimacy thought lost, swept away with a wave of new people, new places, new promise.</p>
        <p>For a while, the two girls would keep it going, he thought, talking once or twice a week, until eventually, unavoidably, one would stumble upon some new diversion, some prospect of fun, a group activity where an old friend might not mesh, and forget to make time. The friend would still call, often at first, then less and less, perhaps encouraged by an infrequent returned message, an assurance of some meeting that would never quite manage to materialize, and slowly, she would let the connection fade, turning to other friends and opportunities of her own.</p>
        <p>As the distance closed between them, his eyes began to warm. He stopped, and the stream of pedestrians bent around him on both sides. He watched her laugh, leaning forward to touch her friend's arm, an unconscious gesture that conveyed such comfort, such trust. Matthew turned down a side street then, hurried away, and returned to the office with his eyes on the pavement.</p>
        <p>"Okay. All set," Laura announced. "Hey, do you mind if we stop by my brother's house while we're out? I still need to return his duffel bag."</p>
        <p>"You've had it all this time?"</p>
        <p>"Yeah, ever since we got back."</p>
        <p>"Ask him if he wants to meet us for breakfast. We haven't seen him in a while."</p>
        <p>He slid his sockless feet into a pair of weathered old sneakers, a size and a half too big, that had been waiting for him by the door. The big cat bounced in and stood between his legs. Matthew grabbed him up, wrestling him with his free hand, and scratched at his belly through the jungle of fur. He smoothed the wild hairs across the cat's face in exchange for a few half-loving nips at his fingers, and returned the animal to the floor, letting him drop the last few inches, then tugging at his shaggy, pointed ear.</p>
        <p>"He's really getting fat," Laura said.</p>
        <p>"Well, we all are."</p>
        <p>He spun the small brass bar to release the lock, and opened the door to the hall. He closed his eyes and took in a deliberate breath. His hand on the knob, he turned back and looked into the room, taking a moment to study the ornaments that decorated his life with Laura, his treasured toys arranged on a ledge, her framed collage of childhood friends, the furniture they'd shopped for together. Laura tilted her head and caught his eyes.</p>
        <p>"Ready?"</p>
        <p>He nodded, and they went out.</p>
    </div>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
