<?php
$section       = 'Comics Every Day';
$title         = 'Sumo';
$author        = 'Thien Pham';
$date          = '01/01/2013';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>I read another book last year that was illustrated by Thien Pham. "Level Up," written by Gene Luen Yang, told the story of an Asian-American son dealing with the pressure to find traditional success while harboring a consuming passion for videogames, an endeavor held up by his parents' generation (and his own cultural heritage) as frivolous.</p>
<p>In spite of my healthy sense of empathy (I guess I cry at movies now), I grew up a privileged white kid in suburbia, where my interests were continuously encouraged, my whims endlessly supported. I understand and can appreciate that in some cultures, children struggle with expectations not as a form of adolescent rebellion, but as the key to their identity, or as their only chance for a future, but I've always felt too safe to identify personally. So, shallow as it is, what most attracted me to that book was the art. There are also creepy little angels.</p>
<p>But, yeah, the art. "Level Up" is characterized by simple, design-driven cartooning that features intentionally imperfect linework and loose, moody watercolors that create an incredibly nostalgic atmosphere. And as we all know (but still fall for), ever since the videogame generation graduated to the yuppie class, nostalgia is currency.</p>
<p>The book was fine. It probably connected really deeply with a certain subset of young people. I was intrigued by the art, but without it being paired to a personally impactful story, the book felt light. It was pretty good, but maybe unnecessary from my perspective. Is that dickish to say?</p>
<p>So now that artwork has budded off and formed its own organism. "Sumo" is a very small book, in length and scope, about a spurned American lover setting off to start a new chapter as a sumo wrestler in Japan. The book trades heavily in the same quiet, reflective mood as its predecessor, accomplished here through mostly wordless pages and single color pastel shading. Seventy-five percent of the panels look like establishing shots. Wordless comics are normally a huge turnoff for me, but there was just enough dialogue here to make the story coherent without inhibiting the momentum of the reading experience.</p>
<p>The story is told as a series of scenes that jump back and forth without regard for chronology. Coupled with the deliberately indistinct character designs, I only realized toward the end these scenes were related, that they in fact all featured the same character. Maybe that's intentional, but without emphasis, a mystery seems like an oversight.</p>
<p>The art is better here than in "Level Up," pushing further into simplicity and experimentation. The line quality is sketchy, the images deceptively plain. It's the kind of artistically imprecise drawing that tricks amateurs into thinking they have a place on the spectrum of professional cartooning. But it takes a lot of talent to make exactly the right aesthetic choice while giving the impression of carelessness. Infinite monkeys with infinite crayons will eventually lend their sloppy lines to some magical composition, but really great artists can create the same impression with intent.</p>
<p>Ultimately, it's a good comic, if not a great graphic novel. This kind of work seeks more to create a vague sense of longing, not even a clear emotion, rather than to tell a story that a reader can become invested in. Maybe I'm spoiled, but if I'm going to read something book-length, I want it to feel significant. I want it to tell a story that matters. It doesn't have to be serious, but it has to do a job. Even if the intent is just to be silly, it has to do a worthwhile job at it.</p>
<p>If "Sumo" were a twelve page webcomic, I'd be singing its praises right now. It's sweet and small and artful, and often that's all I need from a short piece. But when it's presented as a graphic novel, it automatically compares itself to the classics of the medium, and under that kind of scrutiny, it feels insubstantial. The book has heart, but ultimately all that does is make the reader expect impact, and on that score, it feels empty.</p>
<?php include('includes/footer.php'); ?>
