<?php
$section       = 'Comics Every Day';
$title         = 'Madman';
$author        = 'Mike Allred';
$date          = '01/10/13';
$yearPublished = '1993';
?>
<?php include('includes/header.php'); ?>
<p>Mike Allred is perfectly suited to drawing comics. He is a spiritual descendant of Jack Kirby, a stylistic brother to Jaime Hernandez, from a branch of the family that evolved toward bold-lined contours without the busy hatchwork of their mainstream cousins. Remember the superhero drawing Adrian Tomine did for that Weezer poster? Like that, but with way more drama. Allred's technique is smooth and clean, his poses kinetic, his grasp of anatomy precise. His work is the flawless realization of the ideal of jubilant superheroics, at once fashionably retro and daringly modern.</p>
<p>I've read Mike Allred books before, and they're always a lot of fun. But this is his signature character, the creator-owned project that launched him into the big leagues. This is Madman, the addled-minded misfit superhero who pairs psychotic violence with child-like naïveté and makes it seem charming. He never adheres to his quest to discover his former identity too strictly to engage in some zany adventure. He's never too focused on the dangers in front of him to appreciate the joy of an experience.</p>
<p>Allred scores points for subverting and indulging in clichés by turns, while managing to resist either overly-intellectual deconstructions or easy gimmicks like outright parody. He cleverly demonstrates the absurdity of reflective narration in superhero comics by juxtaposing his own thrilling scenes of costumed crime-fighting against the distinctly mundane image of his hero sitting on the ground writing in his diary, the infantile concentration plainly displayed through his facemask.</p>
<p>Thus privy to the content of Madman's scribblings, we see the refreshing sense of wonderment with which he views the world, always eager to assert his limited mental capacity toward pondering metaphysical questions. Having taken a human life, Madman struggles to comprehend or articulate his own feelings of guilt, to evaluate his own code of morality, but brings to it all the emotional maturity that Archie Andrews might employ in choosing a partner to ask to the Riverdale High School dance. His concern is genuine, but his oblivious nature limits the gravity. Even Madman's costume, an oddly continuous body sock with a goofy drawn-on face and legs that tuck into store-bought boots, while a singular graphic accomplishment that serves Allred well, seems less practical to the character who has to live with it, but who is probably very satisfied without having ever put much thought into it.</p>
<p>Allred's stories boast a cornucopia of nerdy delights. Robots, monsters, time travel, rocket ships. Allred's plots and characters gleefully, un-ironically embrace the tropes of genre fiction. Allred draws comics the way I'd imagine Bill Waterson's Calvin would, with boundless, unself-conscious imagination. He seems to be entirely motivated by what seems like fun to draw, fun to read, like Mike Mignola without the creepy graveyards.</p>
<p>Adorably, Allred's comics are all colored by his wife, Laura. I wish I had a wife named Laura who would color all my comics. That's as cute as a button. Knowing nothing of the Allreds personally, I'm happy to assume their relationship to be as sweet as Madman's own chaste flirtation with his love interest, Josephine. Either way, the couple's artistic collaborations are wonderful. Mrs. Allred's style is almost as recognizable as her husband's, with her vibrant palette and restrained shading (only some barely-there blue to shape the hero's dimensions within bounds of his all-white costume) imbuing the story with buoyancy and grace. Separately, they are significant talents. Together, compounded by the cuteness factor, they are greater than the sum of their parts.</p>
<p>I don't know why I haven't read Madman until now. I was always aware of it, always suspected it could be something I would love. Maybe part of me wanted to save it. For a rainy day. For a special occasion. For a good old fashioned good time reading superhero comics when I was starting to feel a bit too cynical. I could probably do with another dose. I could see myself reading a lot more of this.</p>
<p>In fact, you know how good Mike Allred is? Tomorrow: more Allred.</p>
<?php include('includes/footer.php'); ?>
