<?php
$section       = 'Comics Every Day';
$title         = 'X-Force: New Beginnings';
$author        = 'Peter Milligan and Mike Allred';
$date          = '01/11/13';
$yearPublished = '2001';
?>
<?php include('includes/header.php'); ?>
<p>This is not that kind of X-Force. In the late 80s and early 90s, Rob Liefeld made a name for himself drawing superheroes with guns bigger than your arm and arm muscles bigger than, well, also your arm. He got so popular plying this trade on Marvel's X-Force, the aggressively militant faction of the group of super-powered mutants known as the X-Men, that he eventually abandoned them to co-found Image comics, which thrives today in part because they have since set their standards so much higher than Rob Liefeld.</p>
<p>In 2001, when Liefeld's brand of testosterone-driven comics was dying, X-Force was handed off to the new class to be reinvented. Peter Milligan and Mike Allred's first act as stewards of the X-Force legacy was to abandon every character and every concept they'd inherited, so much so that the series would soon be retitled. "The X-Statix" instead took a satirical approach to a story about a group of quirky, vain superheroes who saved the world professionally, not for the good of mankind, not even for the savage thrill of victory, but as a business venture, merely to facilitate their own celebrity status. They never cared about being "heroes," but were intent on pursuing fame and fortune by any means available to them, the reality TV stars of their day. The creators won critical acclaim for using the superhero genre, once synonymous with uncompromising virtue, to highlight the growing emphasis of American society on selfishness and ego.</p>
<p>This is how much of a dork I am: I learned all this long before I ever tracked down a copy of the books. Instead, I had to rely on a Marvel Encyclopedia I bought, which explained in detail the powers, origins, and exploits of every major (or mid-level) character in the Marvel Universe. I read it cover to cover. This is an example of my tendency to hoard pop culture knowledge, which I believe I've mentioned. Mothers, this is what becomes of letting your sons spend too much time rereading the reverse side of trading cards as a kid.</p>
<p>Well, now I've finally read it, and I very much enjoyed it, though the social observations mentioned above are not presented with much subtlety. The characters openly discuss their financial ambition and indifference to helping people, which makes the book less literary than it could have been. Characters basically explain the joke to readers, instead of allowing the theme to dawn on them as they become invested in the story, but the dialogue is no less expository than your typical superhero comic of the time, and the tone never suffers, so it gets a pass.</p>
<p>X-Statix is funny, too. I mean, the old X-Force was funny, but this one is funny on purpose. It sets a tone of high-stakes dark humor that makes sport with life and death. The characters all have their own distinct personalities, their own agendas, and the interactions that ensue drop the friendly "banter" (a word so overused in comics that it's now ruined), for legitimate bickering and pettiness.</p>
<p>There have only been a few Marvel comics that made it their primary goal to be funny, while maintaining a commitment to satisfying action. The best of them is Warren Ellis' "Nextwave: Agents of H.A.T.E.," an absurdist parody of S.H.I.E.L.D., Marvel's resident counter-terrorism force. "Great Lakes Avengers," comprised of superheroes without sufficiently impressive powers to make the official team, arrived on the scene in 2005 to allow Marvel to poke fun at its own very successful "Avengers: Disassembled" event. And similar in theme to X-Statix, though more specifically targeted and more purely comical, the "New Warriors" mini-series from Zeb Wells re-imagined a never popular team of young, street-level superheroes as not just more spoiled denizens of reality TV culture, but as the stars of an actual reality TV series, before the events of "Civil War" permanently obliterated not only their reputation, but also their career prospects, by killing most of them.</p>
<p>But where Marvel couldn't commit to leaving the New Warriors dead, X-Statix had suffered no such qualms. The book makes a point of the team's high turnover rate, and though the circumstances of certain character deaths are designed for humor, the featured players are so well defined that even the permanent death of a brand new character inspires genuine shock. Odd that amid all the superhero comics that present themselves as dark and gritty, it's a comedic soap opera book that adheres to real-life consequences, and makes the reader feel the loss.</p>
<p>Again, Mike Allred delivers. This book is even more graphically, cartoonishly violent than Madman, and though Allred doesn't slouch on the gore, his trademark pop art style keeps the violence in the realm of fun, not terror. The character and costume designs are fun and original. The interpersonal moments are rendered in expressive detail, what you might call "good acting." Most notably, the action is frenetic, with each panel in each fight scene launching some warrior through the air in an inventive acrobatic pose that would do Todd MacFarlane's Spider-man proud.</p>
<p>Though it jumps right into the day to day matters of the team, this volume mostly serves as an origin story, detailing the circumstances of the team's formation as its roster continues to evolve. The external conflicts are not as memorable as the internal ones. The villains are not as interesting as the heroes, which is a good indicator of the depth and humanity of your protagonists, but a red flag signaling that your popularity will face limitations. In today's event-driven comics market, where "epic" (also ruined) is the buzzword that gets a project off the ground, no one wants a quiet story that makes a point. Or if they do, no one's making Marvel money off of it. I guess that explains why you don't see any X-Statix comics on the shelf today. Their spot now belongs to a newly relaunched, commercially thriving X-Force book in the spirit of Rob Liefeld.</p>
<?php include('includes/footer.php'); ?>
