<?php
$section       = 'Comics Every Day';
$title         = 'Ultimate Adventures';
$author        = 'Ron Zimmerman and Duncan Fegredo';
$date          = '01/13/13';
$yearPublished = '2002';
?>
<?php include('includes/header.php'); ?>
<p>In 2000, Marvel launched its "Ultimate" line, which sought to capture new readers by telling stories of familiar characters who inhabit a new universe, divorced from the inaccessible, decades-long continuity of their regular series. The flagship title, "Ultimate Spider-man," quickly accomplished that task and has remained a popular, best-selling title ever since. Many such reboots were attempted, not to replace, but to run in parallel to their historically-minded counterparts. Ultimate X-Men ran for 100 issues. The Ultimates, a re-imagining of The Avengers, found success as a series of critically-acclaimed mini-series. Practically every Marvel Universe property got a shot at Ultimate fame, often powered by top tier creators, to varying degrees of success. The least well-known of these was the feebly-titled "Ultimate Adventures."</p>
<p>At first, this fact is a bit baffling. I'd never heard of Ron Zimmerman, apparently a transplant from television, but aside from some long-windedness, the script is solid. The humor keeps pace throughout, and the premise is a proven winner: the whole thing is an overt parody of Batman. But Zimmerman makes it his own, too, zigging where DC zagged, and I found myself compelled to follow the characters not for their familiarity, but for their originality. When Jack Danner's parents were killed, they left him with considerable means and a motive to take to the streets, fighting crime by night, not with powers, but with training and guts, as Hawk-Owl. But Danner doesn't harbor any deep-seated depression. He doesn't brood. He's a big, goofy kid with a positive attitude, and when he decides to take in a troubled young ward to train as a sidekick (an endeavor he soon reconsiders as profoundly inappropriate), he does it through the proper channels, by formally adopting a son. It's a fun twist on and old favorite that does justice to itself and its source.</p>
<p>Added to that, artist Duncan Fegredo is a major talent with some high profile work under his belt. The book looks great. But there's a reason it looks great: it took an average of almost three months to produce each monthly issue.</p>
<p>When I noticed the sudden, dramatic drop in art quality at the beginning of issue four, I immediately began mentally preparing another rant on the interruption of a book's visual signature, but when I flipped back to the credits page, I got a shock. All six issues of Ultimate Adventures were illustrated by Duncan Fegredo. I flipped forward again. It can't be, I thought - this guy sucks!</p>
<p>Come to find out, issue four featured a guest inker, where Fegredo had handled the brush himself for the other five of six. It's astounding the difference this makes. When Fegredo inks his own work, the art feels balanced, bold. The shadows are so thick that you almost have to trudge through them, which is offset by loose, confident linework in the open spaces for the perfect compositional effect. I'm sure this other inker is good at what he does, but perfectly clean tracing is exactly the opposite of what is so appealing about Fegredo. Clearly no one bothered to show the new guy that the book had established a distinct visual language, and he inked it the way he might any other artist, without any interest in customizing his technique to capture the attitude of the original.</p>
<p>I wasn't able to determine what caused the delays that doomed the series, but Fegredo has always managed to stay busy in the industry, and Hollywood crossovers (Kevin Smith, Damon Lindelof) have a tendency to stretch themselves too thin. That's speculation, though, and to be fair, nobody had to be brought in to trace Zimmerman's scripts, so who knows? Either way, these substantial delays would explain why nobody could be bothered to pay much attention at the time, and why it's fallen into obscurity since.</p>
<p>How obscure? Well, did I mention that I wasn't able to find anyone talking about why this book was late? On the internet? Maybe people just aren't that interested in complaining about comics over the web. The other indication? I didn't buy this comic at the comic shop, nor did I happen across it squeezed between two thicker volumes at the bottom of a Barnes & Noble shelf. No, I came to own my paperback copy of Ultimate Adventures at a discounted price of $3.97 at Books a Million. Swear to God, less than four dollars. And while this arrangement worked out great for me, it does have larger implications. Maybe I'd be willing to admit that, while a fill in artist does disrupt the sanctity of a single artist's vision, under certain, dire circumstances, facing the possibility of permanent irrelevance, maybe, just maybe, it's better just to get the damn thing done. </p>
<?php include('includes/footer.php'); ?>
