<?php
$section       = 'Comics Every Day';
$title         = 'Terminal City';
$author        = 'Dean Motter and Michael Lark';
$date          = '01/14/13';
$yearPublished = '1996';
?>
<?php include('includes/header.php'); ?>
<p>I've read this book before. I've bought this book before. I already own this book. But this new edition also collects a follow up series that I didn't know existed, a series that was never collected on its own. So, while the graphic novel that I read for today also comes in the form of a separate book, the one for tomorrow technically isn't a book. Today's comic is both a book and part of a book. Tomorrow's was only ever part of a book, though it tells a complete story of its own. I don't care. I'm counting them as two books. I make the rules.</p>
<p>So, I've read the first book before. And I bought my new copy after starting this project to eat up my unread books. So this was my bad idea: in spite of my overarching goal to physically move weight from my "unread" pile to my "read" shelf, all I accomplished was to move a single volume (that counts as two) directly from the shelf in the store to my "read" shelf, totally ignoring my expansive backlog.</p>
<p>But this is a special book. I hadn't heard of the series when I found the first volume, either. I wish I could remember where I found it, because I'm sure it must have been one of those great experiences of sifting through stacks of crumbling, forgotten artifacts from another time, then suddenly laying hands on some magical tome, seemingly through a portal to Narnia hidden beyond layers of tattered, yellowing newsprint. As opposed to a quick Barnes & Noble run.</p>
<p>My interest was initially piqued by the art by Michel Lark, the artist of two excellent runs on superhero series that feel more like crime noir, "Daredevil," by Ed Brubaker (doing perfect justice to the mode brought to the book by Bendis and Maleev), and "Gotham Central," the Batman book that Brubaker and co-writer Greg Rucka told from the cops' perspective. Both of these series are among my all-time favorites, and Terminal City promised more intrigue in the same vein. Promised, and delivered.</p>
<p>Terminal City tells a story centered around The Herculean Arms, the premier hotel of a major metropolis, an international hub trafficked by a diverse, colorful population of mobsters and movie stars, politicians and police, dames and daredevils, along with the robots and wage slaves who run the place. It all happens in a then-present 90s that has technologically evolved beyond our own, but without outgrowing such charming old time relics as bellhops, burlesque shows, and black and white newsreels.</p>
<p>Dean Motter crafts the cast and story with great enthusiasm and imagination, like he'd want to be doing it even if it weren't his job. He did for his crime story what David Lynch did with Twin Peaks, what J.J. Abrams did with Lost, what Brian K. Vaughan is doing with "Saga," developing a mysticism around an unusual place by emphasizing the strangeness of the personalities that inhabit it. His script is riddled with references and wordplay, which might be annoying coming from an author less genuinely enamored with the age and the nuances of vocabulary. He's not some hack writing silly jokes and retro set pieces because he thinks his audience is stupid; he clearly loves the atmosphere of the forties as much as the art of the pun.</p>
<p>Surprisingly, happily, the author's sprawling cast overtakes the beautiful design to become the true strength of the piece. Each member of the ensemble adds an ingredient that brings out the best in the others, from the sinister, yet inept French henchmen to the snarky robot hotel manager to the former daredevil turned window washer. Their designs are as distinct as their descriptions: a mysterious stranger in a red Carmen San Diego trench coat, a mob boss who looks like The Little Mermaid's Ursula made human, a police captain in a black turban. Even their names are carefully chosen to create an effect. Though these cutesy gags can often test the boundaries of good taste, as with actor Lance Boyle and triplets Hope, Faith, and Charity, or the obvious homage of Mayor Huxley and his predecessor, Mayor Orwell, the corniness is tempered with restraint, and these winks tend to find their way in organically, so much so that I suspect I missed more than a few.</p>
<p>Lark's art is wholly different here. Though his modern work is also characterized by expertly crafted body proportions, he typically favors rendering them in sketchy lines and shaggy shadows that play out on faces and overcoats in interesting ways. The art of Terminal City relies entirely on outlines and contours of uniform weight. Aside from some gradients that establish the long shadows of twilight across the art deco architecture of the city, the colors are left totally flat, solid colors filling very discrete shapes. The drawings and colors make it immediately clear that this story is different, that it comes from some otherworldly past, even before the gangster slang and screwball plot have their chance. I'm not sure how intentional the effect was, but the combination of a distinct graphical vision (Motter is an innovative designer in his own right), unique subject matter, and a medium in transition converged to create the perfect storm of a unique, memorable aesthetic.</p>
<p>I read the book a lot quicker this time around, nine dense issues in mostly one sitting. A part of that was knowing I had imposed a deadline on myself, and the familiarity also probably carried me along more cozily. I generally don't do a lot of rereading. I read so slowly that revisiting a book feels like a misuse of time better spent seeking out new stories. I've never reread a novel. I've only reread a handful of comics, not just the ones everyone considers to be classics, but books that made a profound impact on me personally, books that played to my own specific tastes or taught me something about the creative process.</p>
<p>The fact that I haven't heard anyone else talking about Terminal City reinforces my connection to it, like the two of us have a special relationship, like it's the mousy girl in English class that only I noticed is actually pretty cute. If that were the case, I don't suppose there would have been a shiny new omnibus edition that hit stores last year. Not exactly the surprise prom queen, but clearly she's spoken for. Still, there's something about the ambitious scope and little details of this story that strikes me just the right way, looks me right in the eye, won't let me dismiss the impossible idea that the magic of the evening will somehow bring us together to share one heartfelt dance.</p>
<p>Maybe two.</p>
<?php include('includes/footer.php'); ?>
