<?php
$section       = 'Comics Every Day';
$title         = 'Terminal City: Aerial Graffiti';
$author        = 'Dean Motter and Michael Lark';
$date          = '01/15/13';
$yearPublished = '1996';
?>
<?php include('includes/header.php'); ?>
<p>The first "Terminal City" series was lightning in a bottle, one of those infrequent occasions where conditions were perfect and everything happened to go just right. The follow up, Aerial Graffiti, carries on in the tradition of the original in all the important ways save one, that elusive x-factor that takes the reading experience from fairly entertaining to genuinely exciting. A lot of the best characters are dead, for one thing, which lent a lot of drama to the climax of the original, but left its little brother with slim pickings. Several new characters are introduced, but mostly they are poor substitutes. The original had a boxer who comes out of retirement to box his way up through the evolutionary ladder, for example. The sequel has a guy who writes swearwords in the sky.</p>
<p>Swearing in fiction is a funny thing. You can't really change the game up. If you go a whole book without using the F word (I'm taking about the word "fuck" here), then you can't use it in the next book. It changes the tone. I don't mean holding it back so that you can give certain moments some extra punch, that's just good practice. I mean taking great care to cultivate a specific atmosphere, making the reader feel comfortable visiting this strange little world, then fucking it all up by changing the rules. What if the sequel to Aladdin had a masturbation scene? (I can't say that it doesn't, I haven't seen it, but that would explain why it went direct to home video.)</p>
<p>The other day, I heard Conan O'Brien using not-safe-for-TV language in his online-exclusive content, and it's weird how titillating that kind of thing can be, not because you thought that never happened, but because it's been so conspicuously absent for so long. I had the same reaction to seeing Stephen Colbert out of character in that video where he welcomes John Kerry to the show backstage. And while both of these examples were more fascinating than uncomfortable, that doesn't change the fact that they were noticeable, jarring. When that happens while you're trying to engage in a narrative, trying to believe in a fictional world, that jolt is enough to break the illusion. I was surprised that Aerial Graffiti didn't account for that. I was disappointed that it didn't make the effort to preserve the same tone it established so well in the first outing.</p>
<p>Over the course of this project, I find myself overusing the word "tone." Monday, the tone is X. Tuesday, the tone is Y. Wednesday, the tone is, not quite Z, but more like a backwards S, but with sharper angles and surrounded by faint, smudgy rubber stamp residue. I have long since run out of synonyms, and must often talk myself down from extending the musical metaphor beyond the threshold of irritability. And while it's creatively limiting to try to find new ways of saying the same thing each day, it says something that I can't help coming back to it.</p>
<p>No conversation about fiction would be complete without discussing tone. It feels pretentious to go on and on about it because it's not a concrete concept, but a subjective observation, depending as much on the experiences that the audience brings with them, so it's easy to start sounding like you're just bullshitting, like inarticulate internet commentators who can always sound superior by falling back to criticizing the "pacing" of a film. (That can sometimes be a legitimate complaint, but at the same time, shut the hell up, you smug bastard.)</p>
<p>Tone is important. Long after I've forgotten the details of a story, after I've read so many other things that I can't keep the plots from jumbling together, I can still remember how the reading experience felt overall. Before I reread it this week, I couldn't have named a single character from the original Terminal City, I couldn't have explained the plot, or spoiled the ending. I didn't remember it that well. But my affinity had never faded because I remembered what it felt like to stand in that city, to hear how the citizens talk, to look up and watch The Human Fly wash his windows. I'd held onto an impression.</p>
<p>There's a reason why I can't bring myself to talk much about the book I read for today. It just wasn't that memorable. It wasn't offensively bad, it just didn't ever grab me like the original did. They even abandoned the flat coloring I appreciated so much, opting instead to overlay faint shadows in the style of 90s action cartoons. It wasn't a total miss. It was great seeing Cosmo and B.B. again. And in the end, despite its faults, Aerial Graffiti did have one good thing that Terminal City didn't.</p>
<p>A robot assassin who speaks fucking Spanglish.</p>
<?php include('includes/footer.php'); ?>
