<?php
$section       = 'Comics Every Day';
$title         = 'Avengers Prime';
$author        = 'Brian Bendis and Alan Davis';
$date          = '01/16/13';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>This might be the least interesting comic I've ever read.
<p>I bought this book because I assumed it was a necessary step in the transition from Marvel's "Siege" storyline into the re-launched "Avengers" title. But I got fooled. Unwilling to follow the crisscrossing course of Avengers continuity from title to subtitle to crossover to miniseries and back again in real-time, I have to just do my best to catch up whenever the mood strikes me. This time the mood struck me during a massive cross-platform promotional campaign in support of the blockbuster film, The Avengers. Lucky coincidence.</p>
<p>Intoxicated with that rarest of sensations, a summer movie that exceeds expectations, I was swept up in a frenzy and bought up copies of any Avengers comics I didn't immediately recognize, confident that I'd adequately, if not thoroughly, calculated the trajectory of the Avengers series. Their strategy apparently worked, because I ended up so confused that I purchased a book I assumed I needed, but didn't, a book I assumed would be at least okay, but wasn't. That's Marvel's goal, right? To beat you up so bad with complicated continuity and release schedules that you just hand over your credit card, no longer caring what you end up with, so long as you're not in trouble?</p>
<p>I didn't know this was gonna be a Thor book.</p>
<p>Can I admit something? I don't think I like Thor. Most writers just assume they can write Asgardian dialogue by throwing in a couple thees and thous and calling it a day. You know, like Shakespeare did. That's bad enough, but move the whole story into Thor's home, the realm of biblical pronouns, and the whole thing becomes incomprehensible, not just because the language is so stilted, but because you can't stand to pay attention to the fantasy clichés. There have been times when Asgard was done well, as when J. Michael Straczynski dropped the whole city in the Oklahoma desert (thereby introducing some characters who don't talk like that, see?), but the odds are against it.</p>
<p>Brian Bendis has written some of my favorite superhero comics. Some? More like half. And there's nothing offensively wrong about this story, except that I just don't care. The big three (Steve, Tony, and Donald) suddenly get transported to the land of the Gods. Where exactly? They don't know, but I don't care. Here come goblins, frost giants, and a village wench who captures Captain America's heart, but can she be trusted? Meh. Here comes the Enchantress, is she the mastermind behind their magical commute? No, here comes Hela, goddess of death, and she's even more Enchanting! Boring.</p>
<p>This artist is boring, too. The art aims for the same comic-booky (this is meant to be descriptive, not pejorative) version of hyper-realism that Bryan Hitch brought to The Ultimates, but about a quarter as detailed. I don't know the name of the artist and I'm not going to learn it, because there is zero chance I will ever recognize his work anyway. It's indistinguishable from any comic drawn in DC's house style. I think it must be him. You know, the guy who draws all the DC comics? That guy.</p>
<p>The book probably cost me fifteen dollars, and took me thirty minutes to read, excluding the nap I took between issues four and five. That's not a joke; I literally put the book down and slept on the couch right before the conclusion. That wouldn't necessarily be a bad ratio if this were a great comic, but I made my own bed so I can't begrudge Marvel. There could have been some huge Thor fans out there who'd waited years for this story to show up and tell a Thor story the right way, and with the eyes of all Avengers fans watching. Somebody out there must have been excited about this thing. The artist's kids, maybe?</p>
<p>But ultimately, for me, the story felt unnecessary. Unnecessary as a bridge (rainbow or otherwise) to connect Avengers storylines, and unnecessary in general. It's not even an Avengers story. It's a Thor story with Iron Man and Cap along for the ride, with the rest of the team presumably off somewhere doing something more interesting. Like silently eating ethnic food. So, unless you were really curious about what Thor's been up to (Asgard has been destroyed again, and this time he's really devastated), and for some reason you refuse to read about it in his own series, I'd skip it. And if that's exactly what you're into, then you may as well wait for the Marvel Masterworks hardcover edition.</p>
<?php include('includes/footer.php'); ?>
