<?php
$section       = 'Comics Every Day';
$title         = 'Patsy Walker: Hellcat';
$author        = 'Kathryn Immonen, Stuart Immonen, and David Lafuente';
$date          = '01/17/13';
$yearPublished = '2008';
?>
<?php include('includes/header.php'); ?>
<p>I watch Project Runway. I could claim that I only watch it to spend time with my wife, but since Season Two, I've become as invested as she is. Certain elements of the show are embarrassing - the affected personality quirks, the false enthusiasm, the way the footage is edited to create drama that isn't there - but I like the idea of television that exposes us to new faces based on their talent, rather than their fervent desire to be exposed. My favorite part of any episode is the half hour they get between having the challenge explained and buying the fabric (or candy, or garbage, or used cell phone parts) where the contestants sketch out their designs. Fashion designers have a distinct and interesting way of drawing, most featuring figures with thin limbs and stark posture, though the execution does vary, above which lie the creativity of the frills and silhouettes of the clothing itself.</p>
<p>I don't know if Kathryn and Stuart Immonen watch Project Runway (I suspect they may be too knowledgeable about fashion to enjoy it, the way doctors can't overlook the minute inaccuracies that must riddle medical dramas like House), but their approach to making Hellcat comics shares some of the same values as those design sketches. Stuart Immonen has been keeping a blog for years, long before it became a compulsory marketing exercise, so I've seen that his dedication to art goes beyond what he's paid to put on a comic book page.</p>
<p>He's published artwork in a diverse array of styles, from the soft, inkless realism of Superman: Secret Identity to the energetic, exaggerated movement of Ultimate Spider-man to the simple, elegant lines of Moving Pictures, another collaboration with his wife, which looks closer to a New Yorker cartoon than their usual fare of superhero comics. Immonen is a perpetual student of art, with influences as diverse as fifties magazine advertisements, eighteenth century French masters, and modern web design principles. If he's going to draw a comic about a fashionable young superhero in Manhattan, he's going to do his research. He's going to make those outfits sing.</p>
<p>A working knowledge of fashion is one strength that Mr. Immonen has over his contemporaries, and an interest he and his wife clearly share. As the writer, she uses Patsy Walker's moments away from crime-fighting (and previously established background as a part-time model) to play dress-up, to flex their fashion muscles, to emphasize the femininity of a female character and to design something rarer in comics and more practical in life than a spandex bodysuit. The Immonens' designs are refreshing in their lack of overt sexuality, sidestepping the implicit demands of stereotypical slavering comic fans to recreate a complex, funny, modern young woman. Patsy Walker's fashion feels genuinely stylish and innovative, as does the fact that her comic even bothered to consider her fashion, and most importantly, it demonstrates to the comics community that there's more to how women dress than attracting men, an important lesson that young people probably aren't hearing enough, girls or boys.</p>
<p>I can't speak with authority about fashion. I can't always follow the conversations that take place on Project Runway. I usually can't remember most of the designs from one episode to the next, but it's cool to see the Immonens find a way to incorporate their own long-standing interests, not typically associated with mainstream comics, into the project, to offer such a unique perspective to an industry that can be fairly closed-minded.</p>
<p>Our happy couple only covers the four backup features that amount to about one issue. For the miniseries that follows, David Lafuente takes over the artwork, and he must have impressed some people, since in the intervening years, he's moved from a five issue minor resurrection of an obscure character to a full-time job drawing Ultimate Spider-man, one of the most popular and controversial titles in Marvel's entire line. Lafuente's work is fluid and light, looser and more dreamlike than Immonen's, but a good fit for the tone.</p>
<p>Immonen's script is smart and fluffy, a story of Alaskan wildlife and Inuit witchcraft that moves quickly and doesn't amount to much, barely touching the continuity of the fictional universe in which it takes place. Though nicely-executed, the reappearance of Patsy Walker, originally conceived (by a female writer) for teen romance comics in the forties and later re-envisioned as a seventies superhero, seems more an experiment in diversifying readership than a serious attempt at popular appeal. But this team of creators puts in the extra effort to give Patsy her own appeal, her own voice, and her own sense of style.</p>
<p>The Immonens were the perfect choice to bring this character out of retirement, the only ones with the qualifications to do justice to both Hellcat and her alter ego. It's fantastic to see a female character given such a strong, feminine persona, whose humor and eccentricity comes from an intention to portray her as a strong, multi-faceted woman, not as the school girl sex bomb fantasy from the mind of some man who relishes the chance to force a beautiful woman to think and act the way he wishes they all would.</p>
<p>The team behind Hellcat delivers an alternative perspective on what is required to tell a superhero story, on how to present a female superhero. This point of view is especially crucial in an industry that always needs more stories and, particularly at this moment in its history, needs more kinds of people to tell them. </p>
<?php include('includes/footer.php'); ?>
