<?php
$section       = 'Comics Every Day';
$title         = 'New Avengers, Volume 2';
$author        = 'Brian Bendis, Mike Deodato, and others';
$date          = '01/19/13';
$yearPublished = '2011';
?>
<?php include('includes/header.php'); ?>
<p>This is the perfect example of the visually disjointed graphic novel, how throwing more and more artists at a comic makes the problem worse, not better.</p>
<p>It starts off strong. After Bendis, a reliable writer who always brings tons of ideas and charm, Stuart Immonen has the next highest billing, lending some visual continuity to bridge the gap from the last volume. He earns that honor, as his one issue has more beauty and subtlety to offer than the rest of the collection combined. Remember how I said Bendis could make a superhero comic with no action scenes so interesting you wouldn't notice? He's literally done that with this issue. The dialogue is so sharp, the artwork so pristine, it manages to become the standout of the collection all the same. I wasn't kidding.</p>
<p>The following issue is another standalone, this time with art by Daniel Acuña, who is unique among mainstream comics artists because he not only inks his own pencils, but colors them as well. Most comics artists have lots of experience with working in color. Many of them are capable of producing extremely polished color work when left to their own devices, but rarely will the deadline-driven comics industry indulge an artist with this level of freedom. Almost always, the art is broken up into three distinct tasks (penciling, inking, and coloring), which are distributed among specialists in each discipline.</p>
<p>Acuña's specialty seems to be combining all three. He has a way of blurring the lines between the stages, a style that leaves some of the work traditionally conveyed through the penciling and inking phases to handle as he colors. No one else could color his work because so much of his work exists as the color. The color itself creates a unique effect. It's glossy and vibrant, and the three phases are so well integrated that the whole composition has the effect of an acrylic painting, but still manages to pay tribute to the traditional pencil and ink method that holds the history of the medium. No one else is making comics that look like this. I've only ever seen a few issues of Acuña's work, but I can already spot his style a mile away.</p>
<p>But Acuña only sticks around for one issue before the book succumbs to Bendis disease.</p>
<p>When I talk about fill-in artists, when I talk about the dead weight from among Bendis' frequent collaborators, when I talk about artists who think that just adding more lines, more muscles, more shadows, is the way to make a drawing really pop, I usually have one particular guy in mind. Time and time again, Bendis delivers killer first arcs, full of intriguing character combinations and inspired plots, and carried off by brilliant artistic collaborators. But sooner or later, every bit of artistic momentum is halted when the art chores inevitably revert back to Mike Deodato, Jr.</p>
<p>I don't want to be unfair. I don't want to sound spoiled or dismissive or elitist. I believe that the art of criticism, at its best, can be a valid and valuable contribution to the cultural community, and that too often, unnecessary, malignant snark demeans the critic as well as the creator. It's easier to stand on the sidelines and yell at the coach than to articulate a constructive argument. It's easier to be funny and get noticed by belittling the efforts of people who take a chance and make themselves vulnerable, and a lot of critics can't resist that temptation, which explains why there can sometimes be such animosity between creators and their critics, and why critics are so often dismissed as talentless, vindictive never-rans, motivated entirely by jealousy and spite. Unfortunately, there is a measure of truth to be found in this idea in many cases, but there are also critics with a great deal to offer, students of art, lovers of art, creators of art, who have a special ability to observe the intricacies in a subject, good and bad, and articulate compelling insights in an entertaining and informative way. Criticism can be as creative as its subject.</p>
<p>I haven't achieved that level of craftsmanship, that level of diligence. I don't always exercise that dignified restraint, but that's one of the things I aspire to. I don't want to be an armchair quarterback. I don't want to indulge in negativity. I want to give credit where credit is due.</p>
<p>Deodato can draw very well, at a level far beyond anything I, or probably anyone I know, ever could hope to achieve. And clearly, he must work quickly, he must be very dedicated, or he wouldn't continue to be tagged in when less reliable celebrity artists can't make their deadlines. But the artwork I've seen from him is disappointing. I'm not angry, Mike Deodato, just disappointed. These pages have no rhythm, no plan. Huge swaths of pure black shadow cover panels and characters in arbitrary arrangements without any sense of balance, searching for a mood at the expense of a coherent light source. He overemphasizes the anatomy, pushing to show more and more musculature regardless of relevance, an off-duty t-shirt bulging with the same thousand non-existent stomach muscles as a spandex costume or bare chest.</p>
<p>His hatchwork can sometimes be inspired, but it is used inconsistently, providing amazing detail in one panel, only to be dropped in favor of smooth blobs of heavy shadow in the next. That inconsistency robs Deodato of a signature style, a reliable, stylistic method of delivering visual information that he could then build off of, improve on, refine. The kitchen-sink/whatever-works/get-it-done approach that keeps Deodato supplied with fill-in gigs is also what prevents him from finding an interesting way to capitalize on his considerable talent. He's a good artist with bad taste, and unless he one day commits himself to overhauling the way he applies his skills, his work will always strike me as generic and ugly. His name on a book cover will always stay my hand, give me pause, his presence a detraction which must be compensated for by other qualities of considerable interest in order to withstand.</p>
<p>Deodato's issues are accompanied in this volume by a series of flashback scenes featuring work from a living legend, Howard Chaykin, who's been a respected contributor to Marvel comics since the seventies. In the last decade or two, however, Chaykin has moved away from the house style he helped solidify to create an identifiable signature characterized by ever-expanding jaw lines and squiggly marks that build up his contours and shading. The effect is unique and recognizable, but at this point, he may have pushed it too far. This is the worst-looking art I've ever seen from Chaykin. He's amped up his trademark heroic head shapes to where every character looks like a variation of the same mongoloid Bruce Campbell. You can almost read the anguish of their mutated cheek muscles in their static expressions.</p>
<p>And the moody, nostalgic coloring scheme only aggravates the issue. I think the intent was to create an atmosphere of hyper-reality, a sleek stillness that made the period feel surreal, but in practice, it just makes all those massive jaws look like they're glowing. Glowing so hard that you have to avert your eyes, glowing so hard they blur their edges, like the neon highlight effect in Tron, or Marlon Brando's silk dress in the opening scenes of the first Superman movie.</p>
<p>So here are two inverse examples of where talent meets style. Both artists possess great talent, but one has no style, the other too much, so neither reaches the potential of his talent. Immonen, on the other hand, has such a brilliant sense of line, that he can deftly adapt his style, customize it to an individual project, make it perfectly suit his subject. Acuña, a new talent, has already managed to establish a definitive aesthetic, and continues to refine it, to push its limits in exciting ways.</p>
<p>Bendis, it seems, has a style of his own. In additional to his funny, talky style of writing, he has a style of choosing collaborators. Half the time he chooses artists with so much style that the finished product exceeds the potential of his words alone, actualizing their potential and adding value. The rest of the time, his style appears to be not to worry too much about style.</p>
<p>Me? I worry. Frivolous as it may be, this is some of the stuff that worries me.</p>
<?php include('includes/footer.php'); ?>
