<?php
$section       = 'Comics Every Day';
$title         = 'Mad About Superheroes';
$author        = 'The Usual Gang of Idiots';
$date          = '01/02/2013';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>I love the phrase "The Usual Gang of Idiots." It conjures an image of the Mad Magazine writing staff sitting around a big boardroom table, the way you imagine the writers' room at The Simpsons or SNL or Conan, middle-aged men with brilliant minds who have dedicated themselves to silliness, not because it's all they have to contribute, but because they believe the world needs nonsense. Not just humor. Not biting wit or political satire. I like to believe these scholars have committed themselves, pledged their efforts in lieu of otherwise promising careers, because they believe a certain amount of utter absurdity is necessary in a society, and because they want to see it done well. Not schlock. The kind of absurdity that's imbued with integrity.</p>
<p>But seriously, these puns are fucking awful. Again, I'd <i>like</i> to say these men are just dedicated geniuses, but the best course for continuing to believe that's the case would have been to go on half remembering decades-old glimpses of the often accurate caricatures and too much text in blocky bubbles to read and never cracking the spine.</p>
<p>In other words, I like Mad Magazine <i>in theory</i>. I mean, those caricatures hold up. Mort Drucker and Tom Richmond know what they're doing, but the fact that I've now learned those names immediately makes me too familiar with the entire product to go forth with rosy goggles.</p>
<p>It's not that I think parody is an inherently frivolous pursuit. A lot of these topics have earned their mockery, and I've been known to oblige them myself from time to time. But I am willing to concede that maybe parody is not the most original form of humor, and perhaps a good percentage of the tradesmen who are attracted to the easiest format also happen to be the ones who go for the easiest jokes. Or choose the least relevant targets.</p>
<p>Maybe that's why they feel the need to parody elements as basic and trivial as the characters' names. Let me come back to that. First, an observation:</p>
<p>In Spider-Man 2, Peter Parker admires a scientist named Dr. Octavius, who tells him that, "intelligence is a gift, not a privilege," which obligates the bearer to strive for accomplishment for the benefit of mankind, an intellectual reimagining of Uncle Ben's classic maxim which states, "with great power comes great responsibility." When the good doctor loses his way, Peter reminds him of his own message, saying, "You once spoke to me about intelligence. You said it was a gift to be used for the greater good..." Seeing the truth in his own reflected wisdom, Octavius chimes in. "A privilege," he agrees, encouraging Peter on toward the conclusion of his big speech.</p>
<p>But wait, Doctor. No. "Not a privilege." That's actually the exact opposite of your statement, which Peter had been managing to remember fairly accurately on his own. Somewhere between the slow motion dives and flailing CG limbs (which I love), the filmmakers forgot what they'd set up to be the moral anchor of the piece, and when it came time for the emotional refrain, the writers were satisfied with a mental grope in the dark back toward dialogue that still existed a clickwheel spin above their flashing cursors. Nobody bothered to actually check. The few lines that drive home the central message at the climax of a multi-hundred million dollar picture that thousands of people contributed countless hours to build, and nobody bothered to be sure.</p>
<p>Some of these subjects warrant parody.</p>
<p>But instead of working hard to identify details and hypocrisies, polishing these moments, applying their finely-honed craft to offer biting criticism, the writers of Mad greedily snatch at low hanging fruit. Without such insights, I may never have discovered that "Peter Parker, Spider-man" sounds a little bit (not a lot) like "Peeper Porker, Spider-Sham." How astute.</p>
<p>Another thing: why do so many of the jokes revolve around the idea that all these movies are offensively awful, empire-crushing failures, in spite of that fact that many of them are not only rather profitable, but in some cases, pretty darn good? Is it just that it's hard to talk about something for that length of time and in that great detail without resorting to the kind of nitpicking that creates an unrealistically negative view of the material? I suppose I can forgive that. Because really, Mad's not actually all that bad either.</p>
<?php include('includes/footer.php'); ?>
