<?php
$section       = 'Comics Every Day';
$title         = 'B.P.R.D. The Hollow Earth and Other Stories';
$author        = 'Mike Mignola and others';
$date          = '01/20/13';
$yearPublished = '2004';
?>
<?php include('includes/header.php'); ?>
<p>The first two volumes in this series, which details the exploits of the Bureau for Paranormal Research and Defense, are each comprised of a grab bag of stories that vary in length, style, and tone, but which all take place in the world of Hellboy, a Nazi-summoned demon turned American federal agent. But by the time the B.P.R.D. got its own series, Hellboy had quit the team and wandered off, so whatever adventures the team embarked on, whatever stories these books sought to tell, they would have to do it without their star attraction. At the outset, this must have seemed a mistake to many. What's Hellboy without Hellboy?</p>
<p>Hellboy is great. He's a strong character with a unique design and an interesting backstory, and he's been the subject of some of the creepiest and most fun comics of the modern era, but the thing for which he is most noteworthy, his best attribute, is the unparalleled brilliance of his creator. If Mike Mignola were still drawing X-Men comics, he'd be the world's best X-Men artist. If he'd taken total control over writing and drawing Spawn, we'd all be buying that book again (this time for the right reasons). If he's created a comic about a three-legged goat wandering through medieval Alaska, he'd make the damn thing work. Hellboy is a great comic because of the man behind it. The beast at the center just got lucky enough to have been created in the right mind at the right time.</p>
<p>The first several volumes of Hellboy are some of the most gorgeous comics ever created, and as you read through them, you can see the evolution of a profound style take shape. The first book features tall, thin characters, more developed faces, and more elaborate scenery, though Mignola's signature shadow-blocking is already heavily at play. As the books proceed, he develops his craft by leaps and bounds, ever able to do more and more with less and less, his foreground shadows scaled back to a few expertly-placed shapes, his faces barely more than some quick swipes that still do the job so eloquently, his backgrounds consumed by darkness but with the perfect composition of highlights and features. That much solid black would doom a page by anyone else in the world, but Mignola's design sense is unfathomable. His ability to craft a mood is one of the most precisely-honed forces in all of comics.</p>
<p>By now, whenever Mignola finds enough time to draw a comic, time enough away from maintaining his media empire (which is no greater a reward than we fans of the medium owe him), the juxtaposition of images can be downright poetic. The abstraction and pacing built into his panels, the tendency of his camera to find minor moments and poignant pauses, have become as instrumental in forming the tone of his work as are the lore that informs it or the creatures who inhabit it.</p>
<p>So here, when Mignola first allowed Hellboy's story to venture away from his direct control, I approached the endeavor with some anxiety. You can't improve on perfection, so any digression could only alter the course in the wrong direction. Predictably, my favorite stories from this first collection are the ones that change the least. I am a creature of habit, I cling to the familiar (I am so afraid of change that I get a panicky feeling at the idea of my wife getting a haircut). Matt Smith does the best Mignola impression of the bunch. The tone, the lighting, the composition, right down to the textures. Plus, his two short pieces most closely adhere to the pace and scope of the original Hellboy shorts (incidentally, Hellboy does wear shorts under his trench coat), which makes sense, as they are also the only two written exclusively by Mignola himself. I'd have been happy for Smith to be the official Mignola stand-in for all time, but then, my sort of timid reluctance is the antithesis to the spirit of invention and reinvention that made Mignola the artist I so admire.</p>
<p>In the volume's feature story, Ryan Sook sticks close to the original as well, but adds his own flair. Certain panels, poses, and figures show more of Mignola's influence than others, and in fact, if not for Smith's work, I might have assumed this was as close as anyone could get. But ultimately Sook settles into his own interpretation, and finds a style that has continued to serve him well as he's adapted and refined it for other projects.</p>
<p>Beyond those, there is one further story that takes the style of the Mignola universe outside the reach of his distinct visuals. The last story in the volume sees Abe Sapien, the Bureau's solemn, aquatic investigator, rendered in a far looser, more organic technique. As with the Richard Corben tales in subsequent collections, this last story takes a cue from some of the classic Creepy and Eerie stories that influenced Mignola so much, but whose descendents belong to another stalk of the horror comic family tree. This style is the largest departure from the series' genesis so far, setting the stage for even more dramatic tangents to come, and while I'm not a huge fan of this particular effect, I have to admit that B.P.R.D. would be poorer today if Mignola hadn't been willing to let the look of the series move away from his own aesthetic.</p>
<p>If B.P.R.D. had never been allowed to do that soul searching, if it hadn't been able to peek down some dark alleys, if it hadn't had the freedom to get a little lost before wandering back, it may never have eventually arrived at a guy who was able to instill in it an appeal of its own, a guy who brought it out of its creator's shadow, a guy who found a way to give B.P.R.D. an individual style as iconic as Hellboy's.</p>
<p>A guy named Guy.</p>
<p>Two more quick notes. Ryan Sook's feature story, from which the book takes its subtitle, is the first appearance of Johann Kraus, the spirit medium who is able to join the ranks of the B.P.R.D. thanks to a containment suit that serves as a vessel for his formless ectoplasm. In Mignola and Smith's short, we see the first solo adventure of Lobster Johnson, the 30s pulp hero whose ghostly presence can still be found seeking justice against the unpunished. They join a cast led by Abe, and including such other imaginative creations as Liz, the suicidal pyrokinetic, and Roger, the kind-hearted homunculus, to form a band of outcasts every bit as memorable and inventive as the X-Men. Even human characters like director Tom Manning and field coordinator Kate Corrigan are fascinating to read because the bonds between these people are so strong and complex. Without its dedication to creating distinctive characters (with even more just over the horizon), a spinoff like B.P.R.D. would not even have been possible, much less this compelling.</p>
<?php include('includes/footer.php'); ?>
