<?php
$section       = 'Comics Every Day';
$title         = "Avengers: The Children's Crusade";
$author        = 'Allan Heinberg and Jim Cheung';
$date          = '01/24/13';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>If I recall correctly, I had a subscription to the original Young Avengers run in 2004. Is that right? Do they offer subscriptions for limited series? Anyway, I must have read the issues because I remember I loved it and there's no collected edition on my shelf. When you have so many more comics than you can keep track of, this is the sort of investigative logic you have to resort to.</p>
<p>What I liked best about that first run was how the team members grew out of their sidekick-like personas, reflections of their Old Avengers counterparts, to reveal the diverse array of motivations, personalities, and origins that made them special. The series' author, Allan Heinberg (a writer and producer on The O.C., a TV teen soap that wasn't afraid to reference comic books before nerd culture was this popular), did something clever there; he kicked off an original series that got the benefit of familiar characters without having to commit to the cookie cutter personalities we'd expect these clones to have. He found a way to get the best of both worlds. He got the book in all the hands of fans who he knew wouldn't miss any perfunctory Avengers title, then promptly dropped the familiar elements that had drawn us in to tell a story that was compelling on its own terms. It was a bait and switch for our own good.</p>
<p>Hulkling was originally introduced as a Young Hulk, but within a few issues, we learned he was actually an alien shape shifter who'd only temporarily assumed the appearance of the Hulk. Asgardian was sold to us as the Young Thor of the group, but it turned out his weather powers were but one manifestation the magic-like, reality-altering mutant abilities that he now wields in his new identity, Wiccan. Not only that, but Hulkling and Wiccan, it turned out, are gay lovers, which, homophobic Amazon.com reviews aside, is yet another progressive and compelling development, handled here with dignity and humanity.</p>
<p>After a few years of less-than-inspired cameos and yearly event tie-in series, The Children's Crusade returns the characters to their creators for another feature episode of the same big fun from their first outing. This time, the team must navigate the chaos of warring factions like the Other Avengers, Dr. Doom, and Magneto to find the truth of their connection to the Scarlet Witch, an former Avenger whose grief and instability were responsible for the events of several major company-wide events of recent years, like Avengers: Disassembled and House of M. This unofficial sequel deftly wraps up those dangling storylines for an intensely satisfying conclusion. The characters are believable teenagers, and the story is told with the appropriate level of drama, and with plentiful humor.</p>
<p>Jim Cheung is one of the best Marvel artists working today. He does a great job balancing the levels of realism and stylistic embellishment. He has a signature look (impeccably clean cross-hatching that looks modern but pays homage to the historical superhero comic aesthetic), that's neither overpowering nor boring. He can draw scenes with emotional complexity or dynamic energy, intimate moments or explosive action, with confidence and consistency.</p>
<p>I'm too ignorant about art theory to provide valid commentary on the details of the colorist's performance, but let me say this: it feels right.</p>
<p>This was the right team for the right book. I don't care if the issues hit the shelves late month-to-month, this story deserved to be done right. If Marvel had panicked and sent some nobody to speed things along (the artist tapped for the one-issue tie-in included at the end of the collection, for example, which I will now pretend I never read) or hadn't been willing to wait for the original author to return to the series, the momentum would have been spoiled, the cohesion ruined, and instead of a collection that I will likely one day return to, it could only have served as a forgettable bridge from one event to the next, not the epic, re-readable touchstone it is.</p>
<p>I hadn't heard of this mini-series when I found it on the bookstore shelf. It was long, and it was expensive, and I was in the middle of other books, so rather than following my typical impulse and absent-mindedly, eye-glazedly carrying it to the checkout counter, I sat in a chair and read the first two issues to verify the quality before committing. Only then did I carry it off home with me. Something tells me that, with two such dependably excellent experiences from Heinberg and Cheung under my belt, there won't be any need to vet the next book I find with their names on it.</p>
<?php include('includes/footer.php'); ?>
