<?php
$section       = 'Comics Every Day';
$title         = 'B.P.R.D. The Dead';
$author        = 'Mike Mignola, John Arcudi, and Guy Davis';
$date          = '01/26/13';
$yearPublished = '2005';
?>
<?php include('includes/header.php'); ?>
<p>Now we're in the thick of it. This is where co-writer John Arcudi joins the team, the final member of the crew that has manned the ship all throughout its peak years. It's impossible to pinpoint the individual contributions of the two writers, Mignola says as much in his afterword, but he does suggest that, as a rule of thumb, he usually provides the big picture ideas, where Arcudi handles the character development. As a result, I can't isolate any praise due to one creator or the other, but I can say that collectively, they get the job done. I can't tell you exactly what Arcudi brings to the table, but at the same time, if his name was missing from the next collection, I'd be disappointed.</p>
<p>At this point, I almost like this series better than Hellboy. The team dynamic and the process of the investigation always appealed more to me than the ghost/monster/squid stories themselves. I'm usually not a fan of horror at all. I wouldn't care if they were ghost detectives (B.P.R.D.), superhero detectives (Powers), or cowboy detectives (million dollar idea), it's the mystery and the drama that appeals to me, so as long as it's written and drawn well, I'm game regardless of the context. Hellboy, although drawn so well that it will always win any comparison, is less focused, less linear, with more of a spooky, wandering tone than the procedural storytelling of Bureau books.</p>
<p>And speaking of new team members, this is the story that introduces Captain Ben Daimio, the gruff soldier who wakes from death (with a positively inspired facial scar), and is brought on to lead the team in an aggressive assault on the still-growing frogman army. Daimio becomes the group dad that balances out Kate Corrigan's mothering presence. Each character, at various times, has had the chance to kick some ass, but until now the ensemble lacked the aggressive presence they find in Daimio. He's domineering and crude, and his introduction changes the dynamic of the group. He becomes a role model for the impressionable Roger, and butts heads with Liz, who resents his authority and disapproves of his penchant for violence.</p>
<p>With B.P.R.D. headquarters relocated to a massive, abandoned government installation in snowy Colorado, the agents set aside Daimio's insistence that they focus on frog hunting and go exploring in the new compound. Once again, they find the kind of Nazi science, magic monster, dark god-summoning adventures that make the book what it is. No need to spoil the details. If the basic idea appeals to you even a little, you can trust this staff to deliver in execution.</p>
<p>Abe Sapien is largely absent from the festivities this time around. He spends almost the whole arc off on his own subplot, investigating the details of his recently discovered former life, as Edward Caul, a human man who'd lived over one hundred years before. This was one of the most exciting and unexpected revelations from the last volume, and like the reader, Abe is compelled to learn more. His research leads him to Caul's old home, where he's abducted by the psychotic spirit of Caul's wife, who holds him entranced as a devastating storm threatens to destroy the decrepit building.</p>
<p>There's nothing more to say about B.P.R.D. This is the Hellboy spinoff you didn't know you wanted, full of drama and humor, action and horror, character and intrigue. And this is where it gets dependably excellent. Just go read it.</p>
<?php include('includes/footer.php'); ?>
