<?php
$section       = 'Comics Every Day';
$title         = 'The Saga of The Swamp Thing, Book One';
$author        = 'Alan Moore and others';
$date          = '01/03/2013';
$yearPublished = '1984';
?>
<?php include('includes/header.php'); ?>
<p>Alan Moore's run on Swamp Thing is one of those touchstones in the history of comic books that you always hear about. It was Moore's first work in American comics, the beginning of an accomplished career that includes the creation of the universally revered, groundbreaking classics "V for Vendetta" and "Watchmen," unimpeachable epics that finally, publicly forced the comic book into the respectable literary realm once and for all, and set the template for the originally intriguing but often-abused "dark, gritty" tone, the influence of which still dominates the superhero genre. Moore began developing that tone (the well-executed, genuine article, far superior to his imitators) with Swamp Thing. His were the first American comics since the fifties to reject the voluntary, yet omnipresent Comics Code Authority in order to tell mature stories for older readers. Moore broke the taboo, and he did it with a vegetable.</p>
<p>Almost as early, Frank Miller also became a key contributor to the trend of dark superhero stories, but he did it with characters like Batman and Daredevil, whose popularity had already been established, and managed to survive the era. Although he's now experiencing a resurgence, I'm told, Swamp Thing has spent more than two decades enveloped in irrelevance, if spared from total obscurity by foggy recollections of a short-lived, low-budget TV series. Moore's stories, in addition to being worthy of preservation and reverence for their historical impact, were also genuinely revelatory, but time has done Moore a disservice by obscuring the subject of these revelations. How insightful to cast Swamp Thing, not as Alec Holland, a scientist whose body was transformed into a living mass of vegetation by a horrific accident, but rather as the sentient plants themselves, holding onto the imprint of a humanity that never belonged to them. How disappointing that this revelation so radically reinvents a backstory that most audiences hadn't known to begin with. Not Alec Holland?! My God! Who the hell is Alec Holland?</p>
<p>Nonetheless, this is a book that had always felt like a hole in my cultural education. People talk about this. I don't know which people, but somebody must, because having skipped over it for this long has always made me feel like a cheater. That's one thing it has in common with Neil Gaiman's "Sandman," but not the only thing.</p>
<p>Both books are widely respected, if only beloved by their respective cult followings. Sandman is the "Nightmare before Christmas" of comic books, a legitimately compelling piece of fiction that holds the annoying association of having been adopted by goth tourists.</p>
<p>Both books cultivate a tangibly creepy mood, not just with macabre, psychological plots delivered through densely-written, descriptive narration, but with distinctly eighties art styles, early experimentation with sketchy textures and atypical hatching schemes that attempt to stretch the boundaries of printing techniques that were about to become obsolete. These pages show their age, and I don't always love the results, but at least someone cared enough to make them their own. You can tell the artists were pushing themselves. This was a time when would-be superstar artists like Mike Mignola and Bill Sienkiewicz were expected to work within the limitations of a house style. The writers weren't the only ones forging new paths.</p>
<p>Both books are critically acclaimed runs on DC-owned properties by British creators who have since attained a level of success and celebrity that affords them the opportunity to concentrate on creator-owned passion projects. And in both cases, I've now read exactly one volume of those long runs, and while generally impressed, remain too intimidated and too indifferent to expect to follow through. For the time being.</p>
<p>I have a lot of other things to get through first, as I think I've mentioned.</p>
<?php include('includes/footer.php'); ?>
