<?php
$section       = 'Comics Every Day';
$title         = 'Mighty Avengers: Siege';
$author        = 'Dan Slott, Khoi Pham, and others';
$date          = '01/30/13';
$yearPublished = '2010';
?>
<?php include('includes/header.php'); ?>
<p>Another volume of Mighty Avengers mismanaged by author Dan Slott. At least this is the last one. Let's make this quick. A few observations:</p>
<p>1. The recap page in this volume is written in the form of a blog post from Stature, a teenage superheroine and part-time member of the team. Not only is this a vain, inefficient way to deliver the information readers need to know, but it's also handled without any common sense. It never occurred to the author that in the context of a public-facing page on the internet within the world where these characters exist, certain recent events are not suitable for public consumption. What we need to know going in as readers doesn't match what Stature's fans get to hear about.</p>
<p>If Stature's post were in continuity, she'd be revealing too much about the personal and strategic details of the Avengers. Is it in continuity, though? It seems the author decided not to worry about that. This oversight is relatively minor, but it demonstrates a fundamental lack of critical thinking on the part of the author. Why should we care about any story if even the writer can't be bothered to care?</p>
<p>2. One of Bendis' early tactics in distinguishing this series from the darker stories being told over at its sister production, New Avengers, was to restore the use of the thought cloud. In the context of modern comics, it was an unconventional, goofy idea intended to lighten the tone of the book. Slott immediately abandons that idea, reverting to the "gritty" tone that pervades superhero comics that take themselves too seriously, trying to compete with his own "epic" storylines, but he retains the tradition of using the thought cloud, not to be funny, just to jam in some exposition whenever he can't find another place for it.</p>
<p>3. At one point, the Avengers are doubting their value (fishing for compliments?), worried they might not be up to the task of defeating whatever it is they care about this month. Jarvis, the dedicated and invaluable butler, explains that, as a continuous presence across the whole history of the Avengers, he's had the opportunity to observe almost every incarnation of the team at work, adding, "and I say to you, with certainty, that this is a superlative team. One of the best." Aw, the nice old gent is proud of his employers, giving them the confidence they need to win. Another way of looking at it is that Slott is using a beloved character as a mouthpiece to compliment his own writing.</p>
<p>4. When I went back to look though the book again (not recommended) to get the exact wording of that quote, I noticed that Jarvis actually calls the team "superplative."</p>
<p>5. This volume is ostensibly a tie-in with Marvel's major event of the year, "Siege." I read Siege when it first came out in paperback two years ago, so I don't remember exactly what it was all about, but I need not have feared, as the official Mighty Avengers contribution offers absolutely no insight into the event. At the beginning of one issue, certain characters are dead, the team is disbanded, and the members have already moved on. Now that's drama. Marvel and Slott's idea of playing into that storyline is just having more unrelated things go wrong for the Mighty team, same as they do every month. And Ultron is back! Again!</p>
<p>6. At this point, Hank Pym had been named Scientist Supreme by the physical embodiment of Eternity, who he'd recently met on a Science Adventure. The title of Sorcerer Supreme, most famously bestowed on the Stephen Strange, master of the mystic arts, makes a certain kind of sense, as magic is an elusive, fictitious force, the rules of which can be made up to support the whim of the writer. Science is science. To suddenly decide there should be a single entity "in charge" of who is objectively the most powerful scientist in the universe is decidedly unscientific. Again, Slott prioritizes his own dumb ideas above the logic of the story.</p>
<p>7. "Avengers Assemble" is the historic rallying cry that signifies a moment of crisis in which all active members of the team must dig deep and attack as a unified surge against improbable odds. It's also a pithy catchphrase. Either way, it's something special, to be held in reserve and only employed at the exact right moment when it can be given the appropriate weight (much like the word "fuck" in a PG-13 movie). When you find a way to work it in twice per issue, it sorta dilutes the intensity.</p>
<p>I could spend some more time with this post, refine it, craft it into a cohesive piece, worthy of the time it takes to read it, but instead, I'll take Slott's tack to just call it good enough and let it sit. I get paid the same either way, right?</p>
<?php include('includes/footer.php'); ?>
