<?php
$section       = 'Comics Every Day';
$title         = 'Avengers, Volume 2';
$author        = 'Brian Bendis, John Romita, Jr., and Bryan Hitch';
$date          = '01/31/13';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>When I was in tenth grade, I stole a comic book. I was fifteen, and I'd walked to the local suburban shopping center with a girl I liked, probably the first time we'd spent any time alone together, though we never ended up finding the right moment to become more than friends. She was cool - a year older and into things like punk rock and comics. It was her idea to go to the shop. At the time, I hadn't thought about comics in years. She was dangerous, too - had pink hair and a pierced nose and was always getting into trouble.</p>
<p>At the comic shop, she was probably looking around for hip alternative press book like Johnny the Homicidal Maniac, while I explored the fifty cent bins, the table of about ten long boxes filled with loose, unorganized back issues of anything that hadn't sold and never would. I found something I liked, something I wanted, and for some reason decided to skip the compulsory checkout stage. I can't remember whether I had a dollar in my pocket or not, it's entirely likely that I didn't, but it probably wouldn't have mattered. Fifteen is about testing boundaries, discovering yourself, and trying to impress cute girls. It's about doing stupid things for stupid reasons. It's about finding those surreal moments, making those magic memories.</p>
<p>When I got home that day, after my friend had left and I'd spent whatever amount of time swirling with enchantment at how close we'd gotten and aching with regret at how close we hadn't, I reflected on the spoils of the day. I felt a juvenile sense of pride for having challenged myself, having looked into my own unexplored heart and found the capacity to be impulsive, to face danger, to risk. Fifteen is also about searching for who you are, what you're capable of. It's a time when you can excite yourself, when you discover that you posses the power to have what you want, do what you want, be who you want and be with who you want, before you have the maturity to know which of these is worth pursuing.</p>
<p>It was an issue of Spider-man. The artist was John Romita, Jr.</p>
<p>It was the first time I'd seen Romita's art - a structured cartoon style featuring square jaws and square eyes, ridges and drapery made of lots of parallel lines. I've read a lot of Romita since then, including the whole run from which that one issue is drawn. He's one of my favorites, but his style has evolved away from those classic issues, still recognizable but less rigorously adhering to the rules that set his aesthetic apart. Every step he's taken away from what he was, regardless of the greater effect, has left me a little more disillusioned. As his work has grown into something different, some of the magic has faded.</p>
<p>For me, Romita's art is inextricably tied to a time in my life when the world felt exciting and dramatic, full of love and fear, an introspective age of discovery. As Romita moves away from Spider-man, so too do I move away from adolescence. Just as that stage of his career still influences the artist he's since grown into, the rebellious phase I grew out of so long ago is still a special part of the experience that makes me who I am.</p>
<p>So I can't see Romita's modern work without comparing it to another version that will always mean more to me. I can't fairly judge it because I can't be objective. I want it to always be exactly as it was, to be a bookmark that allows me to revisit what it felt like to be young and foolish.</p>
<p>I can't concentrate on a new Romita story, the nostalgia is too strong. I can't concentrate on what it is, only what it is to me, like trying to listen to the old albums you played after your first big breakup.</p>
<p>I don't know what I thought of this comic. I wasn't really paying attention.</p>
<?php include('includes/footer.php'); ?>
