<?php
$section       = 'Comics Every Day';
$title         = 'The Adventures of Dr. McNinja: Night Powers';
$author        = 'Christopher Hastings';
$date          = '02/03/13';
$yearPublished = '2011';
?>
<?php include('includes/header.php'); ?>
<p>The thing that surprises me most about Dr. McNinja, an absurdist webcomic which is atypically released page by page in the form of an action comic book, is that Christopher Hastings can draw really well. The thing that most disappoints me about it is when he can't. He does an impressively professional job, taking the time to put in the tedious work of rendering full backgrounds, in perspective, doing his research and clearly photo-referencing the tricky technical subjects - his automotive drawings are good enough to go right into a magazine ad. I've never in my life taken the time to draw a car this accurately, and honestly, I'll never know whether I can because I'm not likely to try. It's too much work for too little interest, but Hastings does an admirably thorough job. But he often misses the mark (literally) in rendering the most essential, most interesting, most abundant of subjects, the human figure.</p>
<p>The Dr. McNinja design is solid. The body is in proportion, the mask looks interesting, and the uncovered eyes manage to be expressive enough to make up for the rest being covered. But too often, an action panel that has clearly been given a great amount of time in the staging phase features a central figure with appallingly distorted anatomy, with totally mismanaged foreshortening, or in the case of minor characters, with a sketchy, indistinct design. The human body is a very complex, troublesome subject, full of nuance and variation and rules that seem to change with every angle or motion, but it's also the only deficiency that can't be worked around, covered with a clever application of style or concealed behind camera tricks.</p>
<p>Hastings' new colorist, Anthony Clark of the webcomic Beartato (the bear-potato), knows all this. His brilliant but simple cartoon style is as comprehensive and magnetic as any, and even his sloppier style on lazy days has its own integrity, its own panache. I'd love to see Clark handle the entirety of the art chores. His usual bouncy, round figures may not be right for the tone Hastings has in mind, playing it straight with a simple and crisp classic style for the inane humor to play against, but Clark has a mastery, an ownership, of his own aesthetic that makes his art feel overall more legitimate.</p>
<p>The single best thing about this series is that, since each daily strip has been originally published one at a time online, Hastings has taken the time to offer hilarious additional commentary in the form of alt text, collected here as captions beneath each page. Some of the best humor in the book is his insight into the writing process itself, stepping outside the story and leveling with his audience, not allowing the sanctity of the narrative to interfere with the real draw of the series, Hastings' own personality.</p>
<p>There's a reason this comic is so popular, that it eventually found a home in print with one of the most successful creator-owned publishing companies, despite Hastings' hit or miss artwork, despite his stories being little more than delightful nonsense. More important than the art or the story, Dr. McNinja's true purpose is to serve as a delivery system for Hastings' comedic genius. If we all woke up tomorrow and Christopher Hastings was writing a totally different comic, none of the appeal would be lost. The title on the cover, or in this case, the web address, is less important than the name underneath it.</p>
<?php include('includes/footer.php'); ?>
