<?php
$section       = 'Comics Every Day';
$title         = 'Invincible Presents: Atom Eve and Rex Splode';
$author        = 'Benito Cereno and Nate Bellegarde';
$date          = '01/04/2013';
$yearPublished = '2010';
?>
<?php include('includes/header.php'); ?>
<p>I was surprised that I liked this book so much. A couple of years ago I almost bought a collected edition of just the two issue Atom Eve mini-series, but managed to resist at the last minute. Now I'm glad I did, because the same issues are collected here alongside three standalone issues of a Rex Splode series. And really, five issues should be a minimum requirement for any collection. Maybe four. If they're great. I mean really great.</p>
<p>Cory Walker, the original artist of the main "Invincible" series (and a personal favorite), was doing a daily sketch blog at one point (Blogging everyday for a year? Impossible.), and somewhere along the way, he graciously decided to share some of his spotlight with a similar project by Nate Bellegarde, an artist with whom I had previously been unfamiliar, but who went on to draw both of the series collected here. I was not immediately blown away, but that probably had more to do with the unfair comparison that his close association with Walker had triggered in my mind. Bellegarde was a fine artist, but there are hundreds of fine comics artists. After reading so many comics for so many years, I suppose I've developed certain tastes, and it takes a special meal to make me take notice. To earn a place at my table, an artist has to not only be great, but must also be unique, and must appeal to my own particular palette.</p>
<p>Plus, nobody new looks great when my next thought after hearing his name mentioned immediately goes to Cory Walker, whose clean, unembellished lines and simple, yet elegant design sense are the epitome of artistic efficiency.</p>
<p>The writer, too, was unknown to me. The original series, like all of Robert Kirkman's work, can sometimes resort to overwritten, exposition-heavy dialogue, but it can also be very clever, and the progression of the storylines in all his ongoing series are always masterful, always addictive. But an unknown (and possibly pseudonymous) writer, coupled with the idea of an off-brand tie-in to an ongoing series that I have loved, in part, specifically because of its manageable continuity, did not sound promising.</p>
<p>I quickly came around on both counts. Too often, unknown artists come off as generic. I sometimes worry that publishers give these thankless jobs, a fill-in issue or a solo series for a popular but overexposed character, to some poor workhorse who is technically proficient but who lacks the personal style that makes a project come alive. To my surprise, Bellegarde delivers. He's still no Cory Walker. Nor is he Ryan Ottley, the long-running current artist on Invincible. But Bellegarde not only manages to get the heavy lifting done, he does it with an aesthetic that is identifiably his own, while still not too far off from the from the bubbly lines and expressive faces that readers have come to expect from the Invincible brand. More great work from the regular series colorist also serves to keep the books consistent across the whole line.</p>
<p>Cereno's script was thoroughly pleasant, with sharp dialogue and a distinct sense of humor. The plots were energetic and engaging, though not ambitious, instead content to serve as quiet vignettes that enhance the primary experience, rather than competing with it. These stories don't seek to live forever in our minds the way certain arcs of the best comics do, the way Invincible remains a top tier book volume after volume. But for a light read, as an exercise in world building, to fill in the anecdotal origins of some minor players on the scene, this was a good time. Both title characters (technically sub-title characters), not to mention whole new supporting casts created to stand on a new plane even farther from center stage, all have tons of personality. Cereno's humor reliably hits its mark, which may actually be a slightly better ratio than Kirkman's. I may just have to hold Kirkman to a higher standard when the next volume of Invincible comes around.</p>
<p>As for Invincible Presents, Cereno, and Bellegarde, I'll be keeping an eye out for more from them, too.</p>
<?php include('includes/footer.php'); ?>
