<?php
$section       = 'Comics Every Day';
$title         = 'Guarding the Globe, Vol. 1';
$author        = 'Robert Kirkman, Benito Cereno, and Ransom Getty';
$date          = '01/05/13';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>Remember yesterday when I said that comics that cash in on their success with parallel series tend to suffer from a reduction of quality? Oh, hi, this is my friend "Guarding the Globe." My friend from church. More of my mom's friend, really.</p>
<p>Every bit of the good will engendered by the spectacular execution of the previous tie-in series, "Invincible Presents," is squandered here. The plot is a familiar trope: the premiere superhero team of our time, suffering from diminishing membership and an expanding breadth of challenges, gets organized, calls up some talent from the minor leagues, and goes international. Didn't the Avengers Initiative pull this trick after the Marvel Civil War event? Hell, come to think of it, didn't the X-men have this idea way back in 1970?</p>
<p>I had hoped that the writing partnership of Kirkman, the creator of the original "Invincible" series, and Cereno, the author of the surprisingly strong "Invincible Presents" outings, would balance each other out, the veteran shaping the storyline with his trademark unpredictability, while the new guy used his sharp sense of humor to inject some life into scripts that too often read like an instruction manual. It seems we got the opposite. Maybe Kirkman let the division of labor serve as a crutch, allowing himself to get by without worrying about how the details of his broad outline would be worked out. Maybe Cereno wasn't comfortable enough asserting himself when paired with the prolific mind that spawned the whole universe, preferring to take a back seat. Maybe each writer saw the other as the point man. Whatever the case, neither voice comes through strongly, and the result is muddled, generic storytelling with no point of view.</p>
<p>The art doesn't strike me at all. This is a prime example of how a skillful but indistinct penciling can leave me bored, how I can come away unimpressed by work that is miles beyond anything of which I'd ever be capable. This is an artist who can fill a page with dozens and dozens of cameo appearances by every character in this whole comic universe, in lavishly rendered detail, choreographed with an exemplary sense of composition, while somehow managing to elude any interest whatsoever. Talent is just not always enough. An artist needs a point of view that separates him or her, at least to some degree, from anything I've seen before. If he can't show me something new, then I might as well go back to skimming the thirty-nine Spider-man titles that come out each week instead. I need some innovation. I need some new ideas.</p>
<p>There are actually some really interesting sketches and pinups included in the notes at the end of the book. Freed from the confines of traditionally hatched out action scenes embellished by another man's brush, this guy turns out some pretty nifty material. These behind-the-scenes insights, complete with creator commentary, are always a highlight of any Kirkman-crew book. It's a shame that more of that creativity didn't find its way into the interior.</p>
<p>Not only do the pages end up feeling bland, but as the liner notes appear to hint, the artist fell out of contact toward the end of the run and had to be replaced for the last issue on short notice.</p>
<p>This is a huge pet peeve of mine. Even on a book that wasn't stellar to begin with, nothing hurts the integrity of a collection more than when a publisher decides a monthly deadline is more important than preserving the consistency of the aesthetic. An issue only stays late for a month, but once the book is out, a disjointed story arc becomes a permanent record of that failure of cohesion. For the most part, I believe that comic books have moved out of the realm of periodicals. People are no longer just buying these things on cheap newsprint to entertain their kids for a few minutes and then toss out. This is someone's art, someone's contribution to the vast landscape of creativity that will live on forever in our collective consciousness, and these days, probably in the digital ether, as well. Once something exists, it cannot be unmade, even after every physical trace of it is destroyed.</p>
<p>When some editor makes the decision that a deadline is more important than the permanent legacy that a work of art leaves behind, it's a signal that this particular offering isn't worth a legacy in the first place, so why should I bother with it either way?</p>
<?php include('includes/footer.php'); ?>
