<?php
$section       = 'Comics Every Day';
$title         = 'Rocketo: Journey to the Hidden Sea';
$author        = 'Frank Espinosa';
$date          = '01/06/13';
$yearPublished = '2006';
?>
<?php include('includes/header.php'); ?>
<p>Frank Espinosa is a hell of an artist, a fertile creative mind, and considering his association with both Disney and Warner Brothers, he's probably a good animator, too. Unfortunately, he's not much of a writer. "Rocketo: Journey to the Hidden Sea" is one of the least professionally written comics I've ever read. The underlying story is solid, a futuristic pulp opera about a brave adventurer and his crew of misfits seeking to re-map the world (and find their fortune) after disaster rends the planet's terrain. But the script itself is not only infuriatingly clunky, it's also riddled with middle school-level typos and grammatical errors.</p>
<p>I suspect that, to a lot of visual artists hoping to strike it big with a creator-owned comic book, "writing" just means thinking up a story, and beyond that, they're content, if not enthusiastic, to just blurt it all out. Espinosa's enormous wealth of supplemental material and plans for follow-ups attest to his imagination and prolificacy. But you aren't really a writer if you don't care about the crafting stage of telling a story. The delivery of the facts is as important as the plot itself, and if not presented in a thoughtful, articulate, efficient way, even a truly great tale is all but wasted.</p>
<p>The odd thing is that this collection had a co-writer. You would think that when an artist crosses over into writing by creating his own property, and someone decides that he should be paired with a writer, it would be because the latter has experience that the former lacks, and could serve as a mentor to usher him into the process, familiarize him with the intricacies that may not have otherwise occurred to a first timer. Mike Mignola, for one, demonstrated great humility in seeking out such assistance in the writing of dialogue for the first volume of Hellboy, though his solitary efforts in subsequent projects bear this out as perhaps an unnecessary precaution.</p>
<p>While Espinosa obviously had a lot on his plate, taking on the roles of plotting, scripting, penciling, inking, coloring, and lettering (which are typically divided among a whole staff of creators), his accomplice presumably had but one task, to refine and elevate the written word itself.</p>
<p>You wouldn't know it from the finished product. This feels like a first draft. Maybe the co-writer didn't feel suited to the material. Maybe she did recognize the ineptitude of Espinosa's writing and was able to offer genuinely helpful input that was then ignored by a proud, oblivious creator who reserved the right of final approval. I can understand that frustration. If I were her, when I saw that this was how the finished product had turned out, I would have wanted to ask for my name to be taken off. A bad writing sample is worse than a blank résumé. If I were a publisher, I would have required the creator to submit to heavy revision by an editor with final approval, or else I'd have had to pass on the project altogether.</p>
<p>This is a story that should have had a lot of momentum, with the visuals leading the reader through a fast-paced adventure. Instead, every page is a chore requiring minutes of slogging through and deciphering talky dialogue, heavy-handed narration, and place names that read like bad fantasy clichés.</p>
<p>Some books warrant this style of dense writing. A great comic book writer consciously controls the pace with which his or her readers move through the pages. "Watchmen" tells a complex, literary story. "The Dark Knight Returns" takes a cue from hard-boiled detective stories. Rocketo was clearly conceived as a sprawling adventure, but its contemplative pace is noticeably at odds with its content.</p>
<p>The art, though gorgeous, tends to emphasize aesthetic appeal at the expense of clarity. The drawings are great, but the choice to color panels primarily in monochrome makes the pages feel flat, more like concept sketches than moments in a scene.</p>
<p>Espinosa would also be better served by farming out the lettering chores. His choice to render speech bubbles with opaque pastel backgrounds and no stroke is obtrusive, as are the colorful, free-floating, tiny triangles that serve as their tails, giving the effect that the page has been sprinkled with confetti. The sound effects are lazily applied in the same thin font as the dialogue, only bigger and more colorful, making them look like placeholders. The whole lettering scheme is clearly an afterthought. Any artist with Espinosa's design background ought to know better.</p>
<p>Rocketo had the potential to have been something very special. When I found it on the shelf, I was immediately drawn in by the visuals, shades of Darwyn Cooke filtered through the anatomical abstractions of the Sunday funnies. If I'd taken more time, standing in the store, to thoroughly explore it, I might have noticed more of the minor visual flaws, but I couldn't have anticipated storytelling missteps this egregious.</p>
<p>When choosing new comics to explore, I make it a point to err on the side of optimism. I'll gladly take a risk on something unfamiliar if it means I might find the next Bryan Lee O'Malley, Jeffrey Brown, or Kate Beaton. As a result, I find myself owning dozens of volumes of comics I don't feel strongly about, books that never capitalize on their potential, books that are fine but don't make a connection, books that don't inspire me. In short, books that aren't worth owning.</p>
<p>Rocketo is a particular disappointment because it came so close to greatness, then fell off so hard. Espinosa has the talent as an artist and the enthusiasm as a creator to have made this a great piece of fiction, but he didn't exercise the self-awareness to recognize his own deficiencies and seek out equally talented collaborators to take his work to the next level. This embarrassment could have been prevented if his editors at Image would have stepped in. This is their failure, too. Rocketo has the makings of a great adventure story, but because care wasn't taken to polish it into its best possible presentation, it falls painfully short.</p>
<p>That said, it might make an excellent basis for a cartoon feature. If they could find a writer.</p>
<?php include('includes/footer.php'); ?>
