<?php
$section       = 'Comics Every Day';
$title         = 'The Strange Talent of Luther Strode';
$author        = 'Justin Jordan and Tradd Moore';
$date          = '01/07/13';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>I'm not in love with the cover of this book. Before I decided to read "The Strange Talent of Luther Strode," I must have noticed it on the shelf eight or ten times. My local comic shop (Local Heroes in Norfolk, VA - recommended) featured the first volume on its new and notable shelf in the early weeks after its release, among the other twenty-or-so books that the owner (Greg - nice guy) and staff had selected to highlight. Needless to say, this is a nook I frequent. I don't go out of my way to follow what's happening in comics week to week. I don't do internet research to find out what people are reading, what people are buying, or even what I should look out for that people aren't buying. I don't follow mainstream trends anymore and I don't have a pull list. I just go to the store and start making a pile of things that jump out at me.</p>
<p>Often, when I catch a jumper, all I need is a quick peek before I know it belongs back on the shelf. Sometimes, the peek leads to a flip-through. Now and again, the flip-through warrants a purchase. Eventually, most purchases lead to readings. Every once in a while, the reading makes me fall in love.</p>
<p>Such was not the case with Luther Strode. Luther jumped out, and Luther went back. Luther jumped again, and Luther went away. But Luther's persistence paid off, and a handful of Luther peeks finally earned a flip-through. This time, Luther had things to show me.</p>
<p>Maybe the reason I took some convincing was that cover. Before a solid red background, a single, bulky figure with feathered blonde hair and Dwight from Sin City's bandage mask raises his bloodied fists, ready to do some damage. I'm not sure what about Luther's image originally turned me away. Maybe those golden locks were just a little too pointy, a little too manga. Maybe that dark outfit was a little too bland, those shoulders a little too hunched. Or maybe it was the Unknown Soldier's bandage mask. Or Darkman's.</p>
<p>When I finally took a deeper look, I found the interior art far more captivating. Hey, his hair's not really that spiky! He starts out skinny! Luther's a regular Joe Highschool, complete with bully and girl crush accessories! That's not even really a bandage he's wearing. I don't know what the hell that is. Luther accompanied me to the checkout counter, where the clerk readily endorsed my decision.</p>
<p>The premise, as author Justin Jordan explains in his introduction, is twofold. First, what happens when an ordinary, Peter Parker-type kid gets ahold of one of those Charles Atlas ads that actually works? Second, how would that weakling react when he suddenly attained the power to eviscerate his enemies with his bare hands? A familiar proverb, an established archetype, but Jordan sells it with his energy and flair. Luther Strode is a bucket of fun.</p>
<p>Jordan's partner is Tradd Moore, which the internet assures me is the name of a human man. Bulkfisted covers aside, Ol' Traddy Tradd was hiding some talent of his own. His thin, organic lines and expressive facial contours are reminiscent of Ryan Ottley's work on "Invincible." My friend, I am always looking for the next Invincible, have I mentioned that? There is a cartoonish element about those faces, too, in the lighter moments, an exaggeration of shapes and angles owing something to Humberto Ramos, perhaps, or like what I wanted "Chew" to be. And something about the stylistic way he articulates those taut lines of drapery evokes John Romita Jr.'s millennial hot streak on "Amazing Spider-man," one of the books that first brought me back to the loving arms of comics after my own Peter Parker impression ended with my graduation from high school.</p>
<p>And those bloody fists, now I see them for what they are. They are a parody of vulgarity, a cheeky grin that dares comic shop browsers to be cynical about their violence. Those cherry fists are a dapple of corn syrup compared to the ocean of plasma that roars through the pages within, a tsunami of gore that rushes over scenes to deliver a beautifully indulgent current of savory hyper-violence. I mean that in a good way. You know, for fun.</p>
<p>Incidentally, the web page that just illuminated the identity of Mr. Moore for me was his personal blog, which also happened to be featuring some more recent Luther Strode art at the time. Let me say, these drawings are... notable. Based on what I saw there, I will be reading subsequent volumes of Luther Strode, no matter how pointy his hair gets.</p>
<?php include('includes/footer.php'); ?>
