<?php
$section       = 'Comics Every Day';
$title         = 'Swamp Thing: Raise Them Bones';
$author        = 'Scott Snyder and Yanick Paquette';
$date          = '01/09/13';
$yearPublished = '2012';
?>
<?php include('includes/header.php'); ?>
<p>I've been hearing people talk about this book. I've been hearing people talk about this writer, who is also the author of the recent Batman relaunch (which I still have not read yet, only because I am not satisfied with the formats in which it is currently available). Well, now I've read this book, and now I've read this author, and now I have an opinion. But I don't really want to talk about it. I'm more excited to talk about something related.</p>
<p>In 1982, Wes Craven, before going on to create "A Nightmare on Elm Street" and "Scream," among other things, wrote and directed a low budget adaptation of Swamp Thing, which is available now on Netflix Instant. I know because I watched it, though I use that term loosely, because I did fall asleep at least once. That's right, I'm excited to talk about a movie that put me to sleep from boredom. Such is the paradox of The Swamp Thing.</p>
<p>The film features Adrianne Barbeau, then wife and muse of John Carpenter, as Alice Cable. Right away, this is an odd choice. In 1982, Barbeau was 37, with a face that looked older and a body that looked younger. I apologize that this statement sounds sleazy, but its accuracy outweighs my guilt.</p>
<p>Moreover, "Alice Cable" is a weird amalgam of references to the source material, where Swamp Thing's love interest is Abigail Arcane, niece of the evil Dr. Anton Arcane. Since Arcane is the film's main villain, but their relationship is not explored, the filmmakers opted to disassociate them by changing the female lead's name. I say changing her name, not creating a new character, because in the comic, Abby Arcane became Abby Cable when she married Matt Cable. But Alice Cable, from the movie, is unmarried, and pursues a relationship with Swamp Thing. So Matt Cable, who has no role in the movie continuity, donated his last name to a wife from another universe, his first name to me, and went on about his business, not existing. To further complicate things, the first name "Alice" appears to have been pulled out of the blue (except for the first letter).</p>
<p>Let's see, that brings us up to the name of the first character to appear on screen. This is moving slowly. No wonder I fell asleep.</p>
<p>Swamp Thing's human alter-ego, Dr. Alec Holland, a scientist working to develop a formula that will allow plants to enhance their own natural defenses in order to conquer the issue of world hunger, is played by a charismatic Ray Wise, best known as Leland Palmer from "Twin Peaks." Wise is the highlight of the cast, so of course he is quickly killed off and replaced by a stuntman in a green rubber suit.</p>
<p>Holland's adversary, Dr. Anton Arcane, is played with great flourish by someone called Robert Louis, who received top billing in the film despite being 1) totally unknown to me, and 2) fucking terrible. His every line is overacted, over-delivered, the classic Hollywood ham. He asks his assistant for a glass of water with the same delivery that assholes use to perform Shakespeare. I recommend sleeping through these scenes.</p>
<p>Dr. Arcane, who apparently earned his PhD in bothering other doctors, as he is never seen or implied to be doing scientific work of any kind, conveniently has access to a regiment of paramilitary troops, presumably mercenaries who responded to his ad in the theft and murder section of the personals. When Arcane gets ahold of the formula that created Swamp Thing, he tricks one of these henchmen into ingesting a dose with dinner. What follows is one of the great performances of film history, as the hulking brute's casual whining and hand wobbling carry him indiscreetly under the tablecloth, to be replaced by a dwarf actor with some patchy ear hair and boar's teeth glued to his face. Swamp Thing, now imprisoned in a dark cell that robs him of the sun's healing rays, explains to Arcane that poor Bruno was the victim of his own diminutive morality, as the formula only brings out and intensifies a person's true self. Just a reminder, this is a formula that was created specifically to make vegetables stronger.</p>
<p>Bolstered by this new information, and not at all discouraged by the perfect record of two horrible disfigurements for two, Arcane voluntarily drinks the remaining formula, convinced his own essence as a brilliant scientist (with no time for science) will transform him into a super-genius, thus rendering him super able to steal others' research far more efficiently. Instead, his skin immediately boils over and encapsulates him in a wet, blistery cocoon. When he hatches, he's a werewolf with a sword. My only experience with Arcane is the one panel of Alan Moore's first story arc where Swamp Thing finds his corpse, shriveled and pink (not explained, though I suspect mad science was involved), amid the wreckage of his crashed flying saucer. Obviously, werewolf with a sword is the natural progression of that idea.</p>
<p>Meanwhile, Swamp Thing, still confined to his lightless prison, is encouraged by Alice to escape, so he reaches one hand out toward the sunlight beaming in through the bars of his cell, right above his head. Now he's strong again, and they escape. It gets foggy here, but I'm pretty sure Swamp Thing, Alice, and Arcanewolf then flush themselves down an oversized toilet to arrive in the swamp for a final conflict.</p>
<p>Swamp Thing wins. But, amid the struggle, Alice Cable is stabbed in the chest and dies. Then vegetable Jesus revives her with some moss and glowing green magic.</p>
<p>The story ends with Swamp Thing refusing Alice's offer to rejoin his life's work, instead opting for seclusion, and jogging off over the horizon, beyond which likely lies a lot more of the same exact swampland. As he leaves her to reflect on the experience, Swamp Thing insists that she return to the world of men, asking only that she please tell his story, a task she accomplished with a TV series, a Saturday morning cartoon, and a sequel.</p>
<p>... As well as a 2012 comic book series by Scott Snyder.</p>
<p>Snyder's reboot/non-reboot sees Alec Holland returned to human form, never having become a plant monster, but cursed to bear the memories of his alternate self. Having given up on his botanical research, he is approached by an emissary of "The Green," the force of nature that protects all the plant life of the world, and informed that he has been prophesied to become their greatest champion. There are also vague references to "The Red," which I suspect is some flesh-based equivalent, but opposition arrives in the form of the Anton Arcane, a sadistic child whose deep connection with "The Rot," the forces of death and decay, grants him the ability to control anything he encounters that is, shall I say, "less than fresh."</p>
<p>Abby Arcane returns as Holland's love interest, only now, thanks to whatever the hell has been going on with DC's revised continuity, she rides a motorcycle. And she has short hair. So clearly she is an ass-kicking, shoot-first-and-ask-questions-later super-bitch, AKA a strong female character.</p>
<p>The book is well-written, though the looming threat of "The Rot," more of a foreboding presence than a villain, recalls to mind another vague, definitely be-articled enemy from across the aisle, "The Void" from Marvel's "The Sentry." In both cases, having otherwise articulate characters suffer and lament over the menace of an abstract dread sounds suspiciously like Goth poetry. Each time some soothsayer warns against "The Rot coming to consume the world," I have to cringe. "The Rot" may as well be called "the darkness, the blackness in my soul." Gross.</p>
<p>The art can be spectacular, at times. Yanick Paquette leads the charge with superior craftsmanship and a ratio of realism to artistic license that evokes Tony Harris's work on "Ex Machina." Unfortunately, DC hedges their bets against cohesion, as usual, by handing off certain chapters and seemingly arbitrary pages to lesser talents. DC is the worst offender in this regard. Almost nothing I've read from a modern DC book has maintained a regular artist through even a single arc. I wish they would either learn to live with the delays or distractions involved with hiring their ideal candidate or just settle for someone dependable from the beginning. Visual continuity is essential when you want your readers to think of an arc as a whole story, a self-contained module, as opposed to just the next several issues of some editorial rambling. This is one of the main reasons that I don't end up reading much of anything from DC's modern slate.</p>
<p>Paquette and crew also favor irregular page layouts, with odd panel shapes and organic filigree serving as gutters. There is artistry not just in the scenes that the story presents, but in the presentation itself. Personally, I found all this ornamentation distracting, but that's a matter of personal taste. I'd prefer that an artist focus on content over artifice, but I can also see how other readers might strongly disagree, and overall, the effect does create a recognizable visual style without harming the reading experience too much.</p>
<p>The story is competently told on both the literary and artistic fronts. It is interesting and novel, though I find that I'm not quite invested in either the theme of man versus nature or the subject of botany. The reading went fast and there was plenty to enjoy, plenty to talk about. Mostly, however, it serves as a reminder of why I don't read DC books. Regardless of the appeal of their characters, the talent of their creators, or the interest of their stories, DC almost always finds a way to get it wrong. An editorial mandate to eliminate existing continuity (while refusing to let it die completely) is a great first move toward that end. Undermining the wisdom of their choice of artists by plugging up holes with mediocre or inconsistent replacements is another.</p>
<p>After all, they let Wes Craven do whatever he wanted with the character, without concern for preserving history or logic. Why not give Scott Snyder the same freedom?</p>
<?php include('includes/footer.php'); ?>
