<?php
$section = 'Comics';
$title   = 'The Happy Detective #1';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content" class="mb20">
    <h2 class="mb20">
        <span>The Happy Detective #1, by Matt Harrison</span>
        <span class="right">07/16/12</span>
    </h2>
    <div class="auto mb20 w500">
        <article>
            <p>Page 1</p>
            <p class="ml20">Panel 1. Lieutenant's door.</p>
            <p class="ml20">Panel 2. Lieutenant seated at his desk, looking stern.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">Detective Tracy, you're making this whole precinct look bad!</p>
            <p class="ml20">Panel 3. Repeated shot, zoomed out. Tracy from behind. Classic yellow trench coat.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">You're a damn good cop, but you're reckless.</p>
            <p class="ml20">Panel 4. Close-up on Lieutenant.</p>
            <p class="txtC">TRACY (O.P.)</p>
            <p class="auto w200">I get the job done, Lieu.</p>
            <p class="ml20">Panel 5.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">Shuttup and listen, Tracy.</p>
            <p class="ml20">Panel 6.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">We have procedures around here...</p>
            <p class="ml20">Panel 7.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">And you need to learn how to work within them.</p>
            <p class="ml20">Panel 8.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">You represent this precinct. You represent all of us.</p>
            <p class="ml20">Panel 9.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">We need to set an example for the community.</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">Why can't you be more like Detective Samantha?</p>
            <p class="ml20">Panel 11. Behind Tracy.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">Oh, right, "The Happy Detective."</p>
            <p class="ml20">Panel 12. Reveal of Det. Tracy's face, looking insulted.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">The Happy Detective can kiss my ass.</p>
        </article>
            <p>Page 2</p>
            <p class="ml20">Panel 1. Three armed men establish control over a bank lobby.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Across town...</p>
            <p class="txtC">ROBBER #1</p>
            <p class="txtC">Nobody move!</p>
            <p class="ml20">Panel 2. A big white van waits across the street.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Outside...</p>
            <p class="ml20">Panel 3. Interior of van. Jimmy at the wheel, looking panicked.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">C'mon, c'mon. What's taking so long?</p>
            <p class="ml20">Panel 4. The robbers burst out of the bank.</p>
            <p class="ml20">Panel 5. The crooks pile in. Jimmy is hesitant.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Sooo... how did it go?</p>
            <p class="txtC">ROBBER #1</p>
            <p class="txtC">Drive, moron!</p>
            <p class="ml20">Panel 6. The getaway car rushes down the street.</p>
            <p class="ml20">Panel 7. A boxy brown sedan trails the crooks.</p>
            <p class="txtC">ROBBER #1</p>
            <p class="txtC">Hey, guys, we're being followed.</p>
            <p class="ml20">Panel 8. A hand props a portable police siren atop the trailing sedan.</p>
            <p class="txtC">ROBBER (O.P.)</p>
            <p class="txtC">It's the cops!</p>
            <p class="ml20">Panel 9.</p>
            <p class="txtC">ROBBER</p>
            <p class="auto w200">Step on it, kid.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">I think it's 35 here.</p>
            <p class="ml20">Panel 10. A bullet erupts through the main robber's face, coating the windshield from inside.</p>
            <p class="ml20">Panel 11. Reveal: Det. Samantha beaming behind the wheel, holding a gun through the shattered windshield.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">This is the part of the job I love.</p>
            <p class="ml20">Panel 12. Samantha jerks the wheel hard, still grinning ear to ear.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Well, heck, I love the whole thing!</p>
        </article>
        <article>
            <p>Page 3</p>
            <p class="ml20">Panel 1. Samantha drives with one hand, holding a bullhorn in the other.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Alright, boys, you've had your fun. Time to face the music.</p>
            <p class="ml20">Panel 2.</p>
            <p class="txtC">ROBBER #2</p>
            <p class="txtC">C'mon, kid, lose this creep.</p>
            <p class="ml20">Panel 3. Robber #2, shot through the body, grimaces in pain.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">I'm gonna pull over.</p>
            <p class="ml20">Panel 4. Detective Samantha pulls the uninjured assailant through the door frame of the van. The others seemingly subdued inside.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Soon...</p>
            <p class="ml20">Panel 5.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">One dead, one injured, but two good collars.</p>
            <p class="ml20">Panel 6.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">All thanks to you, partner.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Yeah, we did OK.</p>
            <p class="ml20">Panel 7. The getaway van peels off down the street.</p>
            <p class="txtC">SFX</p>
            <p class="auto w200">Screech!</p>
            <p class="txtC">ROBBER #2</p>
            <p class="txtC">So long, suckers!</p>
            <p class="ml20">Panel 8. A smiling Det. Samantha takes one shot down the long road.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Oh, no you don't.</p>
            <p class="ml20">Panel 9. The car flips forward in a fiery explosion.</p>
            <p class="txtC">JIMMY (O.P.)</p>
            <p class="txtC">Oh no, Sam. There goes the evidence.</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Not to worry, Jimbo. This crook will just have to plead guilty.</p>
            <p class="ml20">Panel 11. The remaining robber responds nervously, fearing for his continued safety.</p>
            <p class="txtC">ROBBER #3</p>
            <p class="txtC">Sure, man. You got it.</p>
            <p class="ml20">Panel 12.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">See there? All's well that ends well.</p>
        </article>
        <article>
            <p>Page 4</p>
            <p class="ml20">Panel 1. Samantha and Jimmy enter the station with their one remaining perp.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">We got a live one here, Loot.</p>
            <p class="ml20">Panel 2.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">One?</p>
            <p class="ml20">Panel 3.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Plus two dead on the scene.</p>
            <p class="ml20">Panel 4. Samantha absent-mindedly tosses his prisoner into a cell with too much force.</p>
            <p class="txtC">TRACY (O.P.)</p>
            <p class="txtC">One perp? I thought this was supposed to be a big bust?</p>
            <p class="txtC">ROBBER</p>
            <p class="auto w200">Ow!</p>
            <p class="ml20">Panel 5. Sam greets Tracy with genuine enthusiasm.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Black Tracy! Good to see you.</p>
            <p class="ml20">Panel 6. Resentful, Tracy grumbles a response.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">C'mon, Sam. I just saw you this morning.</p>
            <p class="ml20">Panel 7. Lieutenant's door.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Soon...</p>
            <p class="txtC">TRACY (O.P.)</p>
            <p class="txtC">This is BS, Lieu.</p>
            <p class="ml20">Panel 8. Inside the Lieutenant's office.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">Happy Sam kills two perps and I'm the one getting chewed out?</p>
            <p class="ml20">Panel 9. The lieutenant beams with fatherly pride over Samantha.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">A positive attitude goes a long way, Tracy.</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">You're hair looks great, Tracy. Did you get it cut?</p>
            <p class="ml20">Panel 11. Tracy storms out.</p>
            <p class="ml20">Panel 12.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">Forget him, Sam. I've got another case for you...</p>
        </article>
        <article>
            <p>Page 5</p>
            <p class="ml20">Panel 1.</p>
            <p class="txtC">BACON</p>
            <p class="auto w200">Another big day of riding Sam's coattails, eh rookie?</p>
            <p class="ml20">Panel 2.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Leave me alone, Porkins.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">Why does the new guy get all the best assignments?</p>
            <p class="ml20">Panel 3.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">I just wanna do my job.</p>
            <p class="ml20">Panel 4.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">And a darn fine job it was, Jim.</p>
            <p class="ml20">Panel 5.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Got you some coffee, Sam.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Thanks, Champ.</p>
            <p class="ml20">Panel 6.</p>
            <p class="txtC">BACON</p>
            <p class="auto w200">"Got ya some coffee, Saaaam."</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">Did you get me any coffee, Jimmy?</p>
            <p class="ml20">Panel 7.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Leave me alone, guys.</p>
            <p class="ml20">Panel 8.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">A good laugh keeps station morale up.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">See, Jimmy? Happy Sam gets it.</p>
            <p class="ml20">Panel 9.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Little do they know...</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">C'mon, Jimmy. We caught another case.</p>
            <p class="ml20">Panel 11.</p>
            <p class="txtC">BACON</p>
            <p class="auto w200">What? You two had the last one!</p>
            <p class="ml20">Panel 12.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Sour grapes!</p>
        </article>
        <article>
            <p>Page 6</p>
            <p class="ml20">Panel 1.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Ah, my beautiful Jessica. How are you, Detective Monroe?</p>
            <p class="ml20">Panel 2. Reveal: Det. Monroe is gorgeous, the classic blonde bombshell.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">Headed out?</p>
            <p class="ml20">Panel 3.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Big case. Very Dangerous.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">But so are you.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Nothing I can't handle.</p>
            <p class="ml20">Panel 4.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">So, will I... see you tonight?</p>
            <p class="ml20">Panel 5. Close-up. Bedroom eyes.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">...</p>
            <p class="ml20">Panel 6. Close-up. Monroe bites her bottom lip.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">...</p>
            <p class="ml20">Panel 7. The atmosphere changes dramatically.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">You bet! Shelly and I will be over at eight, sharp.</p>
            <p class="ml20">Panel 8.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">Great. My wife is looking forward to seeing you both again.</p>
            <p class="ml20">Panel 9.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Have you seen Shelly around, by the way?</p>
            <p class="ml20">Panel 10. Det. Samantha enters the break room.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Then...</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">We're heading out.</p>
            <p class="ml20">Panel 11. Reveal: Shelly is unattractive.</p>
            <p class="txtC">SHELLY</p>
            <p class="auto w200">OK, honey.</p>
            <p class="ml20">Panel 12. Samantha gives Shelly a peck on the cheek.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Just wanted to say goodbye.</p>
            <p class="txtC">SHELLY</p>
            <p class="auto w200">Try not to get any bad guy blood on your detective uniform.</p>
        </article>
        <article>
            <p>Page 7</p>
            <p class="ml20">Panel 1. Establishing shot. Interior of high-rise office. An Al Capone-style mafia boss sits behind a stately desk.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Masso Family HQ</p>
            <p class="txtC">SFX</p>
            <p class="auto w200">Knock, knock.</p>
            <p class="txtC">HENCHMAN</p>
            <p class="auto w200">Hey boss, the new guy's here.</p>
            <p class="ml20">Panel 2. A bearded young man with glasses, tattoos, and short shorts enters.</p>
            <p class="txtC">MORRIS</p>
            <p class="auto w200">Hey, guy. How's it going? Name's Wolf Morris.</p>
            <p class="ml20">Panel 3. The crime boss looks puzzled, off-put.</p>
            <p class="txtC">MASSO</p>
            <p class="auto w200">Wolf? What kinda name is that? Italian?</p>
            <p class="txtC">MORRIS</p>
            <p class="auto w200">Pfff.</p>
            <p class="ml20">Panel 4.</p>
            <p class="txtC">MASSO</p>
            <p class="auto w200">I've got a shipment of illegal booze coming in tonight. I need you to take care of anybody who interferes.</p>
            <p class="ml20">Panel 5.</p>
            <p class="txtC">MORRIS</p>
            <p class="auto w200">Cool. Look, there's this band playing tonight, so I'm gonna go ahead and get outta here. But I'll be around later. Just text me the details or whatever.</p>
            <p class="ml20">Panel 6.</p>
            <p class="txtC">MASSO</p>
            <p class="auto w200">This is serious business, kid.</p>
            <p class="ml20">Panel 7.</p>
            <p class="txtC">MORRIS</p>
            <p class="auto w200">Yeah, man, kill some cops. No problem. I'll be on it. Later, gator.</p>
            <p class="ml20">Panel 8.</p>
            <p class="txtC">MASSO</p>
            <p class="auto w200">Gator? Carta, get in here. Is saying "Later, gator" cool again?</p>
            <p class="ml20">Panel 9.</p>
            <p class="txtC">CARTA</p>
            <p class="auto w200">Not that I know of, sir.</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">MASSO</p>
            <p class="auto w200">What's with that kid?</p>
            <p class="ml20">Panel 11.</p>
            <p class="txtC">CARTA</p>
            <p class="auto w200">I dunno, boss, but he came highly recommended.</p>
            <p class="ml20">Panel 12.</p>
            <p class="txtC">MASSO</p>
            <p class="auto w200">I don't get it.</p>
        </article>
        <article>
            <p>Page 8</p>
            <p class="ml20">Panel 1. Samantha and Jimmy hide behind some crates on a loading dock.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Jackpot. Here comes the booze.</p>
            <p class="ml20">Panel 2.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">These guys all look like workers. Where's all the security?</p>
            <p class="ml20">Panel 3.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Beats me. Criminals are pretty dim. Maybe we got lucky.</p>
            <p class="ml20">Panel 4.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Wait a minute. This is 2012. Alcohol is legal. What are we even doing here?</p>
            <p class="ml20">Panel 5.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">They're prohibition-era barrels. Confiscated in the 20s, stolen back by the mafia. Huge on the black market. Crooks have a thing for vintage.</p>
            <p class="ml20">Panel 6.</p>
            <p class="txtC">MORRIS</p>
            <p class="auto w200">Did somebody say vintage?</p>
            <p class="ml20">Panel 7. Morris shoots Samantha in the right shoulder at close range.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Sam!</p>
            <p class="ml20">Panel 8. Despite his injury, Samantha lugs his pistol in his right hand.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">No sweat, Jimmy. I've got this guy.</p>
            <p class="ml20">Panel 9. Morris shoots Samantha in the right hand.</p>
            <p class="txtC">JIMMY</p>
            <p class="auto w200">Sam, no!</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">Don't worry, Jim. It'll take a lot more than that to take The Happy Detective out of commission!</p>
            <p class="ml20">Panel 11. Morris snaps his fingers and several henchmen pull automatic weapons on Samantha.</p>
            <p class="ml20">Panel 12. Lying prone on the concrete, Samantha's right arm and side are riddled with bullets.</p>
            <p class="txtC">SFX</p>
            <p class="auto w200">Budda budda budda</p>
        </article>
        <article>
            <p>Page 9</p>
            <p class="ml20">Panel 1. Ambulance rushes to the hospital.</p>
            <p class="txtC">SFX</p>
            <p class="auto w200">Bwee ooo bwee ooo</p>
            <p class="ml20">Panel 2. Samantha on the gurney.</p>
            <p class="txtC">DOCTOR</p>
            <p class="auto w200">Get me 50 CCs of hospital jargon!</p>
            <p class="ml20">Panel 3. Samantha's left hand goes limp.</p>
            <p class="txtC">DOCTOR</p>
            <p class="auto w200">We're losing him!</p>
            <p class="ml20">Panel 4. POV shot from hospital bed.</p>
            <p class="txtC">DOCTOR</p>
            <p class="auto w200">He's been shot fifty times. He'll never move his right arm again.</p>
            <p class="txtC">BUSINESSMAN</p>
            <p class="auto w200">We can rebuild him.</p>
            <p class="ml20">Panel 5. Doctors prepare for dramatic surgery, prosthetics visible in frame.</p>
            <p class="ml20">Panel 7. Samantha looks like Robocop, but can still be identified by his trademark yellow coat.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Then...</p>
            <p class="txtC">ROBO-SAM</p>
            <p class="txtC">You are under arrest. Do not resist.</p>
            <p class="ml20">Panel 8. Repeated shot of thugs with automatic weapons.</p>
            <p class="ml20">Panel 9. Repeated shot of prone Samantha, now as Robocop, being riddled with bullets.</p>
            <p class="ml20">Panel 10. Repeated shot of POV with doctors. Businessman shrugs.</p>
            <p class="txtC">DOCTOR</p>
            <p class="auto w200">Well, that didn't work.</p>
            <p class="ml20">Panel 11.</p>
            <p class="txtC">DOCTOR #1</p>
            <p class="txtC">Put him back?</p>
            <p class="txtC">DOCTOR #2</p>
            <p class="txtC">Put him back.</p>
            <p class="ml20">Panel 12. Repeated shot of doctors preparing for surgery.</p>
        </article>
        <article>
            <p>Page 10</p>
            <p class="ml20">Panel 1. Interior of police station. The detectives are gathered. A "Welcome Back, Sam" banner hangs over the entrance.</p>
            <p class="txtC">CAPTION</p>
            <p class="auto w200">Weeks later...</p>
            <p class="ml20">Panel 2.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">All right, people. Happy Sam will be here any minute.</p>
            <p class="ml20">Panel 3.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">I want everybody to stay positive.</p>
            <p class="ml20">Panel 4.</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">But what about, you know, his injuries?</p>
            <p class="txtC">BACON</p>
            <p class="auto w200">Yeah, pretty gruesome, right?</p>
            <p class="ml20">Panel 5.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">Let's just try to follow his example.</p>
            <p class="ml20">Panel 6.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">That's right. If Sam can keep a smile after all this, we owe him the same.</p>
            <p class="ml20">Panel 7. Shelly helps Sam through the door.</p>
            <p class="ml20">Panel 8.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">Sam, you look...</p>
            <p class="ml20">Panel 9. Close-up on Sam's withered, shaking hand.</p>
            <p class="txtC">LT.</p>
            <p class="auto w200">...</p>
            <p class="ml20">Panel 10.</p>
            <p class="txtC">MONROE</p>
            <p class="auto w200">How do you feel, Sammy?</p>
            <p class="txtC">TRACY</p>
            <p class="auto w200">Yeah, Sam, you OK?</p>
            <p class="ml20">Panel 11. A pregnant pause, his face ambiguous.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">...</p>
            <p class="ml20">Panel 12. His face turns stern forever.</p>
            <p class="txtC">SAMANTHA</p>
            <p class="auto w200">I feel like shit.</p>
        </article>
    </div>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
