<?php
$section = 'Articles';
$title   = 'Riverview Village Days';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content" class="mb20">
    <h2 class="mb20">
        <span>Riverview Village Days, by Matt Harrison</span>
        <span class="right">08/05/17</span>
    </h2>
    <div class="auto mb20 w700">
        <p>Read on <a href="http://altdaily.com/our-local-grassroots-indie-community-riverview-village-days" target="_blank">AltDaily.com</a></p>
        <p>-----</p>
        <p>A few days ago, my wife, Laura, and I wandered for the third or fourth time into The Village Mermaid, an interesting little antique shop near our new house in Colonial Place. The owner, a guy named David Oliver, greeted us amiably and eagerly encouraged us to attend an event his shop would be sponsoring the following day. Riverview Village Days is an open air market that takes place on the second and fourth Sundays of every month from April through December in Lafayette Park, free to attendees and exhibitors, where vendors peddle art, jewelry, and other items of interest to bargain hunters, art enthusiasts, and other neighborhood folks who happen by with a few minutes to peruse.</p>
        <p>We'd attended Village Days before, first at the urging of our good friend and now neighbor Dyanna, as an argument against the idea that leaving Ghent meant leaving behind Norfolk's indie culture and sense of community. We'd toured the tents, flipped through the artifacts, and come away satisfied, with a handmade magnet to show for it, one of those reversible Clean/Dirty indicators for the dishwasher. Months later, we'd walked over again to deliver some mittens to Laura's brother, Adam, who'd been braving the December chill to drum up some last minute pre-Christmas sales for the children's book he'd recently self-published with his wife, and we'd lingered to browse for gifts and to sample some of the treats on offer.</p>
        <p>Speaking with David, I wondered if Village Days might be another good venue to sell my home-printed minicomics. Certainly it would be the closest, and with no charge to qualified exhibitors, the least expensive. I've driven as far as six hours away and paid as much as $300 for comparable space to sell comics, so even if I were to sell only a few copies, I'd lose nothing by spending a few hours in the warm weather, chatting with new people and promoting my work. David easily persuaded me to submit an application.</p>
        <p>The next morning, Laura and I headed over to the park, accompanied by our friend Greg. Initially, we surveyed the grounds together, but each of us was quickly distracted by different booths that appealed to us separately. A lover of garage sale fare, I gravitated toward a box of used paperbacks, then a series of tables bearing quirky old advertisements repurposed as home décor. Greg found a booth specializing in beard oil, an unfamiliar but intriguing product he'd been reluctant to order online, sight unseen. The vendor was knowledgeable and engaging, and with his questions answered, Greg walked away another satisfied customer. Laura, meanwhile, was admiring some custom rings made by a local jewelry designer. When the design Laura wanted was unavailable in her size, the artist promptly brandished her tools and tailored it on the spot. Further down the line, I connected with an artist who'd recently taken up painting while recovering from an injury, and had since begun screen printing his designs onto tie dye t-shirts, with the effect that no two shirts were exactly the same, he explained.</p>
        <p>Other vendors proffered equally unique and diverse items: tabletop terrariums, clay pottery, bars of homemade hand soap. Clustered in one end of the gauntlet was a de facto food court of kiosks and food trucks where customers kept cool with fresh gourmet popsicles or binged on fully loaded burritos.</p>
        <p>Back when we lived in Ghent, we'd explored similar events, but where Stockley Gardens Art Festival, for example, is comprised mainly of seasoned artists offering high ticket items to a more affluent audience, Village Days seems a more modest, grassroots affair. Its vendors are our neighbors, our equals, and perhaps one day soon, ourselves. Part farmer's market, part art show, Village Days has over the past four years cultivated the atmosphere of a Sunday morning stroll pecking over neighborhood yard sales, or scouting a small town shopping district for hole-in-the-wall shops and galleries, a colorful trading post concentrated in one convenient location beneath the shade of the park's tall trees.</p>
        <p>Village Days is an art spot, a locally-sourced eatery, and a hip place to buy neat things you didn't know you wanted. It's a cultural exchange. It's a staple of the community, but also a popup that pops up twice a month. In short, Riverview Village Days is all the things that my wife and I worried we might miss out on by moving out of Ghent. Village Days is the best of Norfolk, right here in Riverview and Colonial Place.</p>
        <p>-----</p>
        <p>Riverview Village Days takes place on alternate Sundays from 11AM to 4PM at the corner of Granby and 38th Street.</p>
        <p>-----</p>
        <p>Matt Harrison is an indie cartoonist and freelance illustrator. His comics and drawings have been published by Whurk Magazine, Southern Grit, and Naro Expanded Cinema.</p>
    </div>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
