<?php
$section       = 'Comics Every Day';
$title         = 'X-Force: The Final Chapter';
$author        = 'Peter Milligan and Mike Allred';
$date          = '01/12/13';
$yearPublished = '2002';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>There is something different about Mike Allred's art in this volume that I couldn't quite place. It feels just slightly different overall, but I couldn't identify any particular characteristic that had notably changed, aside from his tendency to draw characters lips a little larger, a little more loosely. Maybe that one detail betrays an otherwise imperceptible shift, a very deliberate five percent tweak from realism toward abstraction, a course correction that brought the visuals in line with the looser tone of the book.</p>
        <p>The book also includes other, more noticeable visual changes. Two issues in this volume feature guest artists, and while I've mentioned that even a good fill-in artist disrupts the visual continuity of a story arc in an irksome way, single issue contributions from Darwyn Cooke and Duncan Fegredo are about as good a bad mistake as you can make.</p>
        <p>Darwyn Cooke's issue amplifies that cartoony tweak by a factor of five. It looks exactly like a cartoon, even more than his other work, but the integrity and precision he brings to that style is exemplary. It's so loose and fun and free that it elevates the material. Here, the change in artists is mostly forgivable, as it represents a tonal interlude. Cooke's issue sees the charmingly irreverent, blue-skinned Edie hitting the road to reconnect with her roots, with team leader and love interest The Orphan riding along.</p>
        <p>I realize that referring to the characters as "Edie" and "The Orphan" is incongruent, so I will reluctantly mention that Edie's superhero name is "U-Go Girl." Somehow the fact that this is intentionally bad doesn't preclude my disdain. If the X-Men can retroactively remember its female lead as the unadorned "Jean Grey," rather than her short-lived original moniker, "Marvel Girl" (a perfectly fine pseudonym, if inappropriately juvenile by now), then I propose we offer the same courtesy to Edie, whose superhero name clearly warrants whitewashing. The Orphan, meanwhile, formerly known as "Mr. Sensitive," can also be credited as Guy Smith.</p>
        <p>Combined with Cooke's bubbly pencils, the tone of the series shifts out of sync for this issue, a throwback to the pure romance comics of the sixties. As they drive along cinematic vistas of deserted highway, Edie and Guy finally drop the flirtatious enmity and begin to develop a deep intimacy, based as much on bonding over Edie's vulnerable account of her childhood as on their feelings for each other. What could have been a jarring departure is saved by remarkable execution, and instead the standalone issue becomes a welcome distraction.</p>
        <p>Duncan Fegredo's one issue, though it doesn't earn its conspicuousness with an equivalent thematic shift, is still great looking comics when scrutinized out of context. Fegredo's inks exquisitely balance the weight of his compositions with gorgeous texture. You can see every stroke of his brush, every twist of his marker, right on the finished page, and while each panel demands a moment of technical appreciation, it doesn't take you out of the story, either.</p>
        <p>The true outlier in this collection however, is notable not for its divergence from the visual aesthetic, but for the restraint of the author. X-Force #123 is totally silent. Without any dialogue, the issue, which takes the X-Force on a psychedelic journey through the mind of their enigmatic alien teammate Doop, takes less than five minutes to "read." Rarely will a superhero title engage in this particular gimmick, but when they do, it's always an interesting experiment. As an excursion between multiple storylines within a single collection, it serves as an inoffensive but oddball intermission, but I have to wonder whether it felt to monthly subscribers like an annoying indulgence on the part of the author, like the weeks when "Lost" delayed the promised "answers" to explore some minor subplot, or when "South Park" fans became enraged by the writers' failure to immediately fulfill the expectation left by the cliffhanger season finale. Trolls.</p>
        <p>The team name changed at the end of this volume, and subsequent stories appeared under the title "X-Statix." I don't currently don't own any of those four volumes, so if I decide to continue with the series (of course I do), then I'll need to re-invest. This is the root of my problem, the origin of "Comics Every Day." I still own hundreds of unread graphic novels, but the ones I'm most invested in at this moment lie outside that realm. Do I inhibit my satisfaction, and limit myself to playing with the toys I already own? Or do I succumb to temptation, further offsetting my goal of becoming a totally self-actualized comic book reader? Meet me at the comic shop in fifteen minutes to find out.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
