<?php
$section       = 'Comics Every Day';
$title         = 'New Avengers, Volume 1';
$author        = 'Brian Bendis and Stuart Immonen';
$date          = '01/18/13';
$yearPublished = '2011';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>Brian Bendis did it to me again. He's so good at writing team books. He's the gold standard for sparky dialogue, the "superhero banter" that every writer is required to attempt but so few get right. Where many writers struggle to fill panels with anything beyond clumsy exposition, Bendis is so good at making dialogue both funny and tough that you wouldn't care if whole volumes ended up with no action scenes at all. The differing personalities play off of each other in ways so well-observed as to seem both inevitable and unexpected, their interactions fast-paced and witty, even their verbal confrontations dripping with tension.</p>
        <p>When Bendis is on his game, he writes some of the most compelling storylines in mainstream comics, and he's never sharper than when he's launching a new book. Each time an Avengers book gets re-titled, re-launched, or re-imagined, Bendis knocks it out of the park, pairing with a superstar artist (Lenil Yu, John Romita Jr., Stuart Immonen) and serving up classic superhero fare with exactly the right tone of momentous energy. Inevitably, my passion for continuity renewed, I get swept up in the excitement and embark on a shopping spree, compiling every related volume I can gather for another colossal binge.</p>
        <p>The trouble is, the books don't stay as good. Bendis' scripts are almost always great, but he has a tendency (whether due to his own preference or an editorial mandate) to swing back and forth between the best Marvel artists and the most generic. To my taste, it's about fifty-fifty. And a book that might otherwise shine, when filtered through an artist I can't appreciate, can quickly become a chore to read. Comics really are the perfect marriage of art and literature. Unfortunately, rather than great art or great writing elevating its opposite, it's a lot easier for bad art or bad writing to drag down its better half. If one element is lacking, it severely limits the potential of the piece overall.</p>
        <p>This Avengers book is one of those excellent, exemplary first volumes. This is exactly what you want your modern Avengers comics to look and sound like, what you want them to feel like. Bendis has a way of taking seemingly inadvisable plot ideas (putting Spider-man, Wolverine, and The Thing on the Avengers, bringing back obscure villains like The Wrecking Crew or embarrassing relics like Carnage, killing and then reviving the original Captain America) and not only making them feel natural, but saving them in execution, by imbuing them with human drama and unexpected twists. Bendis has been the driving force behind some of Marvel's most stirring events: Avengers Disassembled, House of M, Secret Invasion, Siege. He knows how to shake things up, how to keep the story moving forward in ways that grip the reader.</p>
        <p>This volume sees Bendis teamed once again with Stuart Immonen, who we've discussed. Immonen's art comes alive thanks to expert draftsmanship so efficient and consistent that it looks effortless. He's able to do so much with his subtle mastery of posture and with his thoughtful construction of shadows. All this amounts to an astounding beauty in his pages that is hard to qualify or describe because it's so apparent as to be almost subliminal.</p>
        <p>The plot of this re-launch centers on the reformation of the Avengers B team, sanctioned by but not including Iron Man and Steve Rogers, and headed up by Luke Cage, as they fight a mystic presence that threatens to swallow our world, but we don't need to discuss the details of the plot. Whenever a master like Bendis is joined by an artist of this caliber, the credits page is plenty, you can skip the synopsis on the book jacket. Bendis and Immonen make everything amazing.</p>
        <p>The story, the art, the dialogue, the humor and drama, all make this book a blast to read, but the bigger they are, the harder they fall. Tomorrow, we'll talk about that drop, when Immonen's departure during the next volume leaves the burden tipped heavily toward Bendis, and when his famous friends can't do enough to hold up their end.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
