<?php
$section       = 'Comics Every Day';
$title         = 'B.P.R.D. The Soul of Venice and Other Stories';
$author        = 'Mike Mignola and others';
$date          = '01/22/13';
$yearPublished = '2004';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>The best story of this collection is a backup feature called "Dark Waters," which tells the story of a small Massachusetts town whose one-time witch hunt comes back to haunt them. What struck me most about this story was how memorable the minor characters were. The story does justice to Roger and Abe, of course, the B.P.R.D. agents sent to investigate the town, but these characters have already had time to become established, so as long as a guest writer doesn't stray from the path, they should preserve nicely until the creator returns to give them some authentic development. Genuine advancement of the canon is understood to fall outside the purview of a guest comic, but in the characters created specifically for this story, the inhabitants of this town, who presumably will have no reason to cross paths with the B.P.R.D. ever again, lies a chance for a writer to make his mark. And here, he does.</p>
        <p>The villain is an obsessive preacher who insists on upholding the original conviction of the colonial witch hunt. You can feel the immediacy of his zealotry, the religious fervor that drives his actions. Equally vital is the calm, competent woman who defies the stereotype of the bumbling local sheriff who only impedes the progress of the professionals. Instead, she's funny and helpful, with little experience in paranormal casework, but a quick study and eager to collaborate. Not content with a stock character or mere background player, the author gives us someone we can like, someone we feel like we already know. These little choices make the story more than just another generic diversion to hold readers over while they wait for stories of more substantial length and impact. It's still just an appetizer, but one worth remembering.</p>
        <p>I wasn't familiar with the author of this story, Brian Augustyn, who apparently serves as an editor more often than a writer, but a quick bit of internet research did reveal one title that rang a bell. When I first started collecting Mike Mignola comics, "Gotham by Gaslight" was one of the first, best, and oldest of his graphic novels that I came across. Only fifty pages, the quick paperback re-imagines Batman as a vigilante in the Victorian era, an idea that paved the way for DC's Elseworlds line of alternate reality stories. Based on the strength of this B.P.R.D. entry, that old girl may warrant a reread. That could be a dangerous path to start down, though. That could turn into a whole thing.</p>
        <p>One might think it would be impossible to create distinguishable minor roles in a book featuring demons, reanimated flesh monsters, and human/amphibian hybrids as its regular cast, but Guy Davis, who went on to become the regular artist of subsequent B.P.R.D. books, manages the task. In order to compete, it would be tempting to give every new character a robot hand or eye patch, something distinctive that would allow them to compete with the series' stars for the spotlight, but Davis does it without resorting to gimmicks. The preacher's wild eyes really sell his fanaticism. The sheriff's plump build, sexless hairstyle, and take-it-as-it-comes demeanor firmly establish her as humble, practical-minded small town "folks."</p>
        <p>Davis' artwork is a major digression from the Hellboy family. Almost all the stories in these collections at least try to imitate the heavy shadow that fans immediately associate with Hellboy and Mignola. Davis' lines are sketchy and organic, his inks fast and fluid. He's the only B.P.R.D. artist I've seen that managed to emerge from Mignola's shadow and also look great. I vaguely recall a time when I wasn't sure I cared for his style, but that was years ago, when I read these early volumes the first time, and my tastes have widened and deepened since then. Hellboy was one of the first books that got me curious about the world outside of Marvel and DC. I'm sure that if I could go back and see whatever else I was reading at the time, I'd probably be ashamed of the lack of diversity. Plus, when the best creature guy in the business calls someone new "the best creature guy in the business," you should probably give him a chance.</p>
        <p>The title track (I've decided that can be a thing for books now) is less memorable. I'm actually struggling to remember anything about it at this moment besides the art of Michael Avon Oeming, whose work on Powers has its own distinct appeal, but which never really meshes for me here. Oeming's style has a lot in common with Mignola's, the heavy black shadows and stylized cartoon figures, but not because he's intentionally imitating Mignola; they just happen to have that in common. Unfortunately, the similarity draws an unfair comparison that makes Oeming look worse in this context than he deserves. The writer is a name I've never heard before, and since the story obviously didn't grab me and he doesn't even have a Wikipedia page anyway, I'm not going to bother getting familiar.</p>
        <p>The only other story of note is a Lobster Johnson issue by current DC golden boy Geoff Johns and artist Scott Kolins, whose uniform, thin outlines (Herge's ligne claire, or "clear line" style) are notably different from other superhero/horror fare, but which lack a satisfying level of polish. Rather than long contours that gracefully build out his subjects' forms, Kolins renders texture and shadow as hundreds of short jags and tiny pockmarks that leave the work looking dirty and unfinished. I would say he might be better served by an inker who "got" his drawing style better, but it turns out he tackled the job himself, so I guess that's not a valid excuse. Maybe he should hire an inker anyway.</p>
        <p>The book rounds out with an issue featuring Abe Sapien following a monster under the bed, and a new eight page zombie story created for this collection.</p>
        <p>The next volume moves on to B.P.R.D.'s now standard method of releasing stories as a sequence of miniseries (never committing to an ongoing), with Guy Davis tightly strapped in as copilot. These first two collections, while not as strong as Mignola's solo work or the more focused story arcs that follow, are firmly rooted in the tradition of the creepy horror anthologies that inspired Mignola to become the creator his is today. Like the two volumes of professional fan fiction series "Hellboy: Weird Tales" released in parallel, the individual entries are hit or miss, rarely capable of achieving great storytelling without direct involvement from Mignola, but certainly of interest to a completist.</p>
        <p>But this collection marks a turning point. After this, and perhaps for twenty-some pages during, a window opens that allows B.P.R.D. to exist, not just as some benchwarmer, but as a real player in the game, a teammate and companion to the superstar, often capable of his own remarkable performance. Guy Davis, in his craft and in his consistent presence, makes B.P.R.D. a legitimate contender, worthy of standing alongside the original Hellboy. This series may have started as a goofy little experiment to keep the motor running on the Hellboy universe, but in Davis, Mignola found a collaborator he could entrust with the fortification of his expanded universe. In Davis, Mignola found a worthy custodian.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
