<?php
$section       = 'Comics Every Day';
$title         = 'Mighty Avengers: The Unspoken';
$author        = 'Dan Slott, Khoi Pham, and others';
$date          = '01/27/13';
$yearPublished = '2010';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>There is a way to integrate plot development into dialogue without resorting to transparent exposition. There are ways to do it well, to do it right, but there are many more ways to do it wrong. If you can't think of a better way to communicate that two characters are related than having them address each other as "sister" or "father," shame on you. If you have your protagonist explaining a concept to a peer who would already be familiar with it, you should be a garbage man, not a writer. If you think that reaching for the ten dollar word at the expense of clarity makes you sound impressive, not ignorant, you're fired. You can't trick us into enjoying your story or laughing at your jokes by having your characters tell each other how great they are, how funny that was. We're onto you. We expect more tact from a professional. We expect more.</p>
        <p>When I first started reading comics in earnest, I began by collecting series connected to the characters that introduced me to the medium. At the time, around 2002, in addition to X-Men and Uncanny X-men, there was a parallel series written by Chris Claremont, the author of quite a few classic X-Men arcs from the eighties, called X-Treme X-Men. I eventually caught up to the monthly schedule and read the last of the fifty-or-so issues along with the other subscribers, but I don't even really remember the premise. What I remember (aside from the lame leather overcoat redesigns) are the patterns and tropes that overwhelmed it. I remember the verbose captions and inane dialogue. Every issue saw every character's powers re-explained. Every bubble saw every action transcribed, every motivation made explicit.</p>
        <p>I understood, as I trudged through those uncomfortably dense issues (to which I was nonetheless committed), that Claremont was a holdover from another time. He was still writing comics for the old world, where superheroes were a niche market, still struggling for legitimacy, and new readers didn't have a reliable means to catch up on continuity. He was used to writing comics that anyone could pick up at any given moment, on any given issue, and follow right along with the regulars, the veterans. He was still to writing episodes for a superhero sitcom.</p>
        <p>But comics had changed by then, and they've changed even more by now. Comics are expected to tell complex, ongoing stories, and "any given issue" is now almost certainly but one chapter in a continuing saga. We've arrived in a more elegant age of storytelling, where television dramas, more often than not, choose not to transition new viewers with sloppy, redundant dialogue that eats into the new episode, but with a quick recap up front that then drops us into the story and respects our intelligence enough to believe we'll follow along. Comics are the same. At some point in the first decade of the new millennium, somebody had the bright idea to drop in a page in front that says, "Here's what you need to know."</p>
        <p>Dan Slott's Mighty Avengers is a huge step backwards. The dialogue is some of the clumsiest, most unnatural exposition I've ever read, placing even more strain on a narrative already struggling to be funny or interesting. I'm tired of writers who think writing is just about coming up with a plot, who assume it's as easy as it seems, who don't consider the nuances of character and storytelling. I'm tired of amateurs allowed to masquerade as professionals because the demand for new material is so high. I'm tired of the consumers who devour it all because it's there, without regard for its individual value.</p>
        <p>If this is what we get when we demand more content, let's demand less. Instead of demanding more and more options to choose from, let's demand that fewer outlets take more of that time and energy to make their product the best it can possibly be. Let's stop supporting mediocrity. Let's agree to content ourselves with the precious few offerings that aspire to true art, and let's let all the nonsense die away.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
