<?php
$section       = 'Comics Every Day';
$title         = 'B.P.R.D. The Black Flame';
$author        = 'Mike Mignola, John Arcudi, and Guy Davis';
$date          = '01/28/13';
$yearPublished = '2006';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>The Black Flame is a Nazi super villain in a suit of steampunk armor and a flaming skull helmet, who Mike Mignola describes as the Hellboy universe's version of Doctor Doom or the Red Skull. The design is interesting, but its key feature is a bit too familiar. Marvel, for example, has not only Ghost Rider, but also a gentleman by the name of Blazing Skull, whose appearance I'll leave to your imagination. Open the trope up to include the medium of biker tattoos and the tally grows astronomically. But what's most interesting about B.P.R.D.'s representative in the league of cranial flamers has nothing to do with his costume. In fact, Guy Davis draws the suit so bulky that the villain appears to be rendered nearly inert, a cumbersome Darth Vader getup that looks so heavy, he's only ever seen standing around, more menacing than murderous.</p>
        <p>The Black Flame's intrigue is bolstered by a captivating character arc, though. His icy demeanor in the two board room scenes is particularly memorable. How he behaves when he gets what he wants, and who he's shown to be when he doesn't, reveal so much of his personality with so little said. His relationship with his employees, his research, how he treats their test subjects - these authors are amazingly efficient at conveying the core of a character with so short a term of exposure. This is the reason that changes in the cast in no way threaten the appeal of the book.</p>
        <p>It won't spoil too much (some, but not too much) when I say that the big climax of the collection involves the summoning of an enormous tentacled god who wreaks havoc on humanity. That may sound like too much detail to a B.P.R.D. novice, but honestly, I'm having a hard time thinking of a Mignola story that doesn't end just like that. That's not to say this particular behemoth isn't interestingly designed (a sort of organic, invertebrate War of the Worlds tripod), or doesn't convey the intended menace, it is and it does, but escalating the size of the threat is an unsustainable method of creating conflict in an adventure series. The bigger you make your next doomsday scenario, the less reverence retroactively remains for your previous ones. I'd hate to one day start thinking of the great Mike Mignola as the boy who cried monster squid god.</p>
        <p>The villain is cool (in a half-cool, half-interestingly-uncool way) and the monster is appropriately devastating, but once again, the strongest appeal is the emotional lives of the characters, how the team changes, how they deal with that loss. Likewise, the new and side characters are clearly defined and compelling. Even the villain's frogmen lab rats manage to use their precious little air time to come off a little cute.</p>
        <p>Aside from the smallest reservations about the redundant monster attack scenario (which, to be fair, the frog plague has been building toward all along) and the super villain's forgettable in-costume persona (without the costume, he's fascinating), there's nothing to complain about with this book. The only thing keeping it from perfection is the fact that I need to reserve a comparative tier on my mental shelf to account for the level of quality achieved by the other volumes in the series. The only way I can seem impartial is to force myself to nitpick an arc that would have been a sparkling triumph for any other series. Or maybe I'm just trying to lower my own expectations so I'll be that much more jazzed when I get my hands on the next volume.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
