<?php
$section       = 'Comics Every Day';
$title         = 'Nemesis';
$author        = 'Mark Millar and Steve McNiven';
$date          = '02/01/13';
$yearPublished = '2011';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>Nemesis tells the story of a character who, not unlike Batman, uses the personal fortune left to him by the premature deaths of his parents to dedicate himself to becoming a symbol of perfect conviction to mankind, but in this case, that conviction is to do evil.</p>
        <p>Mark Millar is a strong writer. The intrigue is his stories is rooted in his ability to empathize with any character, no matter how un-relatable they may seem. Millar has a way of finding and articulating an understandable, if disagreeable, motivation to accompany any perspective. In Marvel's Civil War, he renders two dramatically opposed points of view in the right to privacy debate without choosing a side himself, lending equal conviction to either side of the conflict. In Wanted, he manages to make his reprehensible protagonist sympathetic; we so identify with the hero's frustrations that we're tempted to excuse his selfish and destructive behavior. In Kick-Ass, he writes the lead character with such humanity that we almost believe his plan to become a real life superhero is plausible. In each case, Millar shows us enough of ourselves and the real people we know that even if we don't agree with these characters, we can understand them, we can believe they exist. This is the key to good fantasy; regardless of the setting, premise, or circumstances, the characters must demonstrate recognizably human qualities.</p>
        <p>No such insight informs the perspective of this villain. Nemesis is the embodiment of random violence, of obstinately unexamined ruthlessness. His existence is appalling because, though Millar's gift for natural dialogue makes him sound like us, and Steve McNiven's solid, detailed art makes him look like us, he has a viciousness we can never relate to, and he's smart enough to circumvent the consequences. He's the psycho killer we're all afraid is just around every next corner, a detached barbarian with the skill and intellect to ignore the rules of society and get away with it. He's the Joker if he got to win.</p>
        <p>There is nothing of us in Nemesis. Nor is he a proportional representation of the true villains of our world, the brutal dictators, the religious zealots, the unscrupulous politicians. These people do their wrong in service of specific goals, whether wealth, power, or some twisted glory. In Nemesis, we recognize an even more uncomfortable reality. He is a reflection of those outsiders who elude explanation, violent anarchists who seek to destroy society itself, so deranged and distorted that they attack in every direction, randomly, raging against the very idea of humanity. He is an abnormally capable serial killer, a dialed-up mass murderer, a savage sociopath incapable of human compassion. We don't see ourselves in him. We see our fears in him. We see ourselves in the powerlessness of his victims.</p>
        <p>It's a good book, but an unpleasant one. This level of cartoon violence typically has the opposite effect; such blatant exaggeration makes the real thing seem silly, laughably outside the realm of possibility. Here, it's accompanied by such unrepentant maliciousness, so lacking in empathy or explanation, it can't be accounted for. That touches a nerve, because unfortunately, it's not that far from certain rare horrors that exist in our world, too.</p>
        <p>All murders demonstrate a disregard for the value of human life, but most at least offer a context that provides us a measure of exclusionary distance. Well, they were in a gang, he provoked a domestic dispute, she accepted that possibility as an occupational hazard. A random killing has no such context. It suggests that there can be people who hate every person just for being a person, people who would be happy to destroy anyone at any moment.</p>
        <p>Nemesis revels in that possibility, takes it as a premise on which to build a story meant to shock and entertain. It's a well-told story, and it is genuinely shocking, but that's not my ideal form of entertainment. That's true horror.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
