<?php
$section       = 'Comics Every Day';
$title         = 'The Intrepids';
$author        = 'Kurtis Wiebe and Scott Kowalchuck';
$date          = '01/08/13';
$yearPublished = '2012';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/header.php'); ?>
<div id="content">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/header.php'); ?>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?>
    <div class="auto mb20 w700">
        <p>Sometimes I think I need to give up on superheroes. I mean, I'll always eventually wander back and suddenly get excited about whatever Brian Bendis books I've missed, and I'll always have a place in my heart (and on my shelf) for classic Batman stories (and so forth), but I've already had to start ignoring the ins and outs of ongoing mainstream titles entirely. There was a time, in the beginning, when I felt a compulsion to know everything there was to know about a character. If I loved an X-men story, I had to know what came before, what came after, and ultimately, what came first (the mutant or the egg?). Before I discovered the graphic novel, I went so far as to assemble full runs of my early favorites like X-Force, X-Factor, and New Mutants, hundreds of individual issues collected piecemeal from fifty cent bins across the region, supplemented by the occasional Ebay auction to fulfill those elusive slots. I was a completist. I was obsessive. I was organized. I made a spreadsheet.</p>
        <p>I loved those characters. I loved so many of them. But eventually, you get cynical. It's hard to stay enthusiastic once you notice that for every truly spectacular Spider-man story arc that either embodies your ideal of the character or contributes a genuinely impactful reinvention, for each gem, there are countless others that serve no narrative purpose. There's this fluff, the "rough" that overwhelms the diamond.</p>
        <p>Marvel is obligated to its investors to keep the Spider-man brand prevalent. They don't have the luxury of keeping him in their pocket while the perfect creator comes up with an epic worthy of his legacy, they have to keep churning those things out. There are lots of highlights, but far more of it is some guy's best attempt at a quickie epic that's good enough to meet a deadline.</p>
        <p>So if you care more about a good story than staying in the loop, it's not practical to be a completist. After years of obsessing, I had to stop chasing that unending goal, along with the sense of satisfaction that comes with owning all there is to own, knowing all there is to know.</p>
        <p>Third party publishers make it easier. There's a great example I could offer here, but I promised myself I'd stop mentioning "Invincible" every single time I write about comics. Wait... damn it. But yeah, I keep an eye out for the superhero books that seem like they do bother to wait for that great idea. There are lots of good examples. Savage Dragon, Powers, Ex Machina, The Umbrella Academy, The Cape (the comic, not the failed NBC show, which belongs in the other category). Even Hellboy, despite crossing over into mainstream success, is still published through periodic mini-series so the creator can stay involved and vet the quality of each story individually.</p>
        <p>So if I see a new superhero comic on the shelf, I usually give it a chance. Most times, they are just okay, disappointing but not egregious. I can mostly tell when I'm going to love the art, but a lot of times the story doesn't grab me. Firebreather, Winter Men, Gladstone's School for World Conquerors, Grounded. And now, The Intrepids.</p>
        <p>I generally like the art. It looks like a simplified version of Darwyn Cooke's "The New Frontier," a graceful cartoon style that emphasizes bold curvy lines and anatomical constructions that almost allow you to see the geometric shapes beneath, as though they were constructed of tangrams. When done right, it can be marvelous, as in other, better work like Dean Trippe's "Butterfly," or even Bruce Timm's designs for the various DC animated series. The Intrepids doesn't quite master the style. There was one panel in particular with a really troublesome perspective mistake that I can't stop thinking about. But overall, pretty good art.</p>
        <p>The writing isn't great. "The Intrepids" tells the story of a philanthropic scientist who recruits a team of talented teens to track down and eliminate his insane former colleague, but does their mentor have a secret motive? It's a fine premise, but the execution is generic. From the playful art style, I'd hoped this book would be funny. It makes an attempt (if you think blurting out "epic fail!" counts as a punchline), but it also tries too hard to go dark, especially during the flashback sequences, with their altered color schemes and molester-y tone.</p>
        <p>There have been so many writers who have tried to reinvent the superhero team. It boggles the mind that people still show up to work thinking their idea is the one that will blow the whole thing wide open, as though all of the superhero books out there now follow the same formula and this new idea is going to break the mold. There is no mold. "Watchmen" swept the straightforward superhero story off the table, and "breaking the mold" has since become the new mold. Just tell an interesting story. Don't try to present it as another deconstruction. What would happen if superheroes were real? What if superheroes weren't really nice guys? Watchmen. Watchmen would happen. Squadron Supreme would happen. The Ultimates. The Authority. Powers. The Boys.</p>
        <p>Intrepids doesn't really try to reinvent the wheel, I guess, but it does exploit the "gritty superhero" trope, both with its atmosphere of mistrust and with the revelation at the end of the first arc. And it just doesn't do a great job. You know what would really shake things up, turn the industry on its ear? Just write something fun. Somebody, please.</p>
        <p>Speaking of Ebay, one digression:</p>
        <p>Your old comic books are not worth money. As collectors, from time to time we encounter people like you who aren't that into comics, but who still have some of their old ones from childhood that they refuse to part with because, "they'll be worth money some day." No, they won't. You may not realize this, but comics is a mass market industry. To survive, the publishing companies need to make a profit, and to do that, they have to get the books into as many hands as they possibly can. In fact, they usually make more copies than they think anyone would possibly buy, just in case. The business model is to print so many things that the odds dictate that something will have to get popular. They flood the market. The only reason Action Comics number one is worth a million dollars is that no one anticipated that anyone would ever think of bad drawings of blue pajamas on crummy newsprint for children as an integral piece of American culture. Those comics were printed, badly, with the understanding that they'd be snatched up by some kid for a nickel in exchange for a few minutes of entertainment, then tossed out. They were created to be garbage.</p>
        <p>Your copy of Wolverine number 203 is not special or rare. If it were, you never would have stumbled across it drooping over the edge of that Walgreens magazine rack.</p>
        <p>If you were very dedicated, you could probably buy first editions of all the popular comics, seal them in protective sleeves, then carefully watch the market, and maybe you could make a few dollars profit on certain things and lose your investment on many others. But c'mon. You're not dedicated, and you're not careful. You're not even watching.</p>
        <p>All this to say, if I find a shoebox full of old comics in your attic, just fucking let me have them.</p>
    </div>
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/blogs/comics-every-day/nav.php'); ?></p>
</div>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/projects/portfolio/includes/footer.php'); ?>
